import { router } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { Button, Eyebrow, Panel, TeamMark, Title } from '@/components/ui/game-ui';
import { Colors, Fonts, Layout, Radius, Spacing } from '@/constants/theme';
import { STARTER_TEAMS } from '@/data/teams';
import { CAREER_EVENTS } from '@/data/events';
import { useCareerStore } from '@/state/career-store';
import { Personality, PlayStyle, PlayerIdentity, PlayerRole, Region } from '@/types/game';

const roles: { id: PlayerRole; code: string; description: string }[] = [
  { id: 'Entry', code: 'ENT', description: 'Abrís sites y tomás el primer duelo.' }, { id: 'AWPer', code: 'AWP', description: 'Precisión, paciencia y rondas decisivas.' }, { id: 'Rifler', code: 'RIF', description: 'Consistencia mecánica en todos los mapas.' }, { id: 'Lurker', code: 'LUR', description: 'Leés rotaciones y castigás espacios.' }, { id: 'Support', code: 'SUP', description: 'Utility, trades y estructura colectiva.' }, { id: 'IGL', code: 'IGL', description: 'Liderazgo y lectura táctica.' }, { id: 'Hybrid', code: 'HYB', description: 'Adaptación entre rifle y AWP.' }, { id: 'Anchor', code: 'ANC', description: 'Defensa estable y sangre fría.' },
];
const stylesList: PlayStyle[] = ['Aggressive', 'Tactical', 'Clutch', 'Mechanical', 'Team player', 'Star player', 'Utility specialist', 'Defensive', 'Flexible'];
const personalities: Personality[] = ['Ambicioso', 'Disciplinado', 'Carismático', 'Reservado', 'Competitivo', 'Analítico'];

export function CreateCareerScreen() {
  const { width } = useWindowDimensions(); const wide = width >= 900;
  const { career, hydrated, startCareer } = useCareerStore();
  const [step, setStep] = useState(1); const [fullName, setFullName] = useState(''); const [nickname, setNickname] = useState(''); const [city, setCity] = useState('Buenos Aires'); const [nationality, setNationality] = useState('Argentina'); const [age, setAge] = useState(17); const region: Region = 'Argentina'; const [role, setRole] = useState<PlayerRole>('Rifler'); const [playStyle, setPlayStyle] = useState<PlayStyle>('Mechanical'); const [personality, setPersonality] = useState<Personality>('Competitivo'); const [priority, setPriority] = useState<PlayerIdentity['priority']>('Títulos'); const [teamId, setTeamId] = useState(STARTER_TEAMS[0]?.id ?? 'leo');
  useEffect(() => { if (hydrated && career) router.replace({ pathname: '/[screen]', params: { screen: 'dashboard' } }); }, [career, hydrated]);
  const selectedTeam = useMemo(() => STARTER_TEAMS.find((team) => team.id === teamId) ?? STARTER_TEAMS[0], [teamId]);
  if (!hydrated || career) return <SafeAreaView style={screen.loading}><Text style={screen.loadingText}>ROUND/ONE · LOADING CAREER</Text></SafeAreaView>;
  const canContinue = step !== 1 || nickname.trim().length >= 2;
  function launch() {
    const identity: PlayerIdentity = { fullName: fullName.trim() || nickname.trim(), nickname: nickname.trim(), nationality, region, city, age, primaryLanguage: 'Español', secondaryLanguages: ['Inglés'], handedness: 'Diestro', personality, ambition: 82, riskTolerance: playStyle === 'Aggressive' ? 82 : 58, priority, role, style: playStyle };
    startCareer(identity, selectedTeam.id);
  }
  return <SafeAreaView style={screen.safe}><ScrollView contentContainerStyle={screen.page} showsVerticalScrollIndicator={false}>
    <View style={screen.top}><Image source={require('../../assets/images/round-one-icon.png')} style={screen.brandLogo} /><Text style={screen.brand}>ROUND<Text style={screen.orange}>/</Text>ONE</Text><Text style={screen.version}>CS2 CAREER SIMULATOR · v1.0</Text></View>
    <View style={[screen.grid, wide && screen.gridWide]}>
      <View style={screen.hero}><View><Eyebrow color={Colors.black}>COUNTER-STRIKE · CAREER MODE</Eyebrow><Text style={screen.heroTitle}>Del matchmaking{`\n`}al <Text style={screen.heroOutline}>Major.</Text></Text><Text style={screen.heroCopy}>Cada entrenamiento, contrato, derrota y clutch altera una carrera que puede durar más de una década.</Text></View><View><View style={screen.heroRule} /><View style={screen.heroMetrics}><View><Text style={screen.heroNumber}>100</Text><Text style={screen.heroLabel}>equipos VRS</Text></View><View><Text style={screen.heroNumber}>30</Text><Text style={screen.heroLabel}>torneos/año</Text></View><View><Text style={screen.heroNumber}>{CAREER_EVENTS.length}</Text><Text style={screen.heroLabel}>eventos</Text></View></View></View></View>
      <Panel style={screen.builder}>
        <View style={screen.steps}>{[1, 2, 3].map((value) => <View key={value} style={screen.stepItem}><View style={[screen.stepDot, step >= value && screen.stepDotActive]}><Text style={[screen.stepDotText, step >= value && screen.stepDotTextActive]}>0{value}</Text></View><View style={[screen.stepLine, step > value && screen.stepLineActive]} /></View>)}</View>
        {step === 1 ? <View><Eyebrow>01 · IDENTIDAD</Eyebrow><Title size="medium">Creá tu player</Title><Text style={screen.help}>Tu origen afecta idiomas, mercado inicial y eventos regionales.</Text><View style={screen.formGrid}><Field label="NICKNAME *" value={nickname} onChangeText={setNickname} placeholder="K1NG" /><Field label="NOMBRE" value={fullName} onChangeText={setFullName} placeholder="Nombre completo" /><Field label="CIUDAD" value={city} onChangeText={setCity} placeholder="Buenos Aires" /><Field label="NACIONALIDAD" value={nationality} onChangeText={setNationality} placeholder="Argentina" /></View><Text style={screen.fieldLabel}>EDAD INICIAL</Text><View style={screen.chips}>{[15, 16, 17, 18, 19, 20, 21, 22].map((value) => <Chip key={value} label={String(value)} selected={age === value} onPress={() => setAge(value)} />)}</View><Text style={screen.fieldLabel}>PERSONALIDAD</Text><View style={screen.chips}>{personalities.map((value) => <Chip key={value} label={value} selected={personality === value} onPress={() => setPersonality(value)} />)}</View></View> : null}
        {step === 2 ? <View><Eyebrow>02 · IDENTIDAD COMPETITIVA</Eyebrow><Title size="medium">Definí tu juego</Title><Text style={screen.help}>Los bonuses iniciales son distintos y cada atributo entra en la simulación.</Text><View style={screen.roleGrid}>{roles.map((item) => <Pressable key={item.id} onPress={() => setRole(item.id)} style={[screen.roleCard, role === item.id && screen.roleCardActive]}><View style={[screen.roleCode, role === item.id && screen.roleCodeActive]}><Text style={[screen.roleCodeText, role === item.id && screen.roleCodeTextActive]}>{item.code}</Text></View><Text style={screen.roleName}>{item.id}</Text><Text style={screen.roleDescription}>{item.description}</Text></Pressable>)}</View><Text style={screen.fieldLabel}>ESTILO</Text><View style={screen.chips}>{stylesList.map((value) => <Chip key={value} label={value} selected={playStyle === value} onPress={() => setPlayStyle(value)} />)}</View><Text style={screen.fieldLabel}>PRIORIDAD DE CARRERA</Text><View style={screen.chips}>{(['Estabilidad', 'Dinero', 'Títulos', 'Minutos'] as const).map((value) => <Chip key={value} label={value} selected={priority === value} onPress={() => setPriority(value)} />)}</View></View> : null}
        {step === 3 ? <View><Eyebrow>03 · PRIMER CONTRATO</Eyebrow><Title size="medium">Elegí dónde empezar</Title><Text style={screen.help}>Entrás desde Tier 3 o semi-pro. El top mundial se conquista, no se selecciona.</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={screen.teamList}>{STARTER_TEAMS.map((team) => <Pressable key={team.id} onPress={() => setTeamId(team.id)} style={[screen.teamCard, teamId === team.id && screen.teamCardActive]}><TeamMark code={team.abbreviation} color={team.color} size={48} /><Text style={screen.teamName}>{team.name}</Text><Text style={screen.teamMeta}>#{team.initialRanking} · {team.tier}</Text><Text style={screen.teamMeta}>{team.region}</Text></Pressable>)}</ScrollView><Panel style={screen.contractPreview} accent="orange"><View style={screen.contractHeader}><TeamMark code={selectedTeam.abbreviation} color={selectedTeam.color} /><View><Text style={screen.contractTeam}>{selectedTeam.name}</Text><Text style={screen.contractMeta}>{selectedTeam.city} · {selectedTeam.objective}</Text></View></View><View style={screen.contractMetrics}><View><Text style={screen.contractLabel}>SALARIO BASE</Text><Text style={screen.contractValue}>${Math.round(selectedTeam.averageSalary * 0.7).toLocaleString('en-US')}/mes</Text></View><View><Text style={screen.contractLabel}>QUÍMICA</Text><Text style={screen.contractValue}>{selectedTeam.chemistry}</Text></View><View><Text style={screen.contractLabel}>MAP POOL</Text><Text style={screen.contractValue}>{selectedTeam.mapPool.length}</Text></View></View></Panel></View> : null}
        <View style={screen.actions}>{step > 1 ? <Button label="← Atrás" variant="ghost" onPress={() => setStep(step - 1)} /> : <View />}{step < 3 ? <Button label="Continuar →" disabled={!canContinue} onPress={() => setStep(step + 1)} /> : <Button label="Firmar y empezar →" onPress={launch} />}</View>
      </Panel>
    </View>
    <Text style={screen.disclaimer}>Los rankings y rosters usan un snapshot público de Valve del 03/08/2026. Los valores financieros y de gestión son parámetros de simulación aproximados.</Text>
  </ScrollView></SafeAreaView>;
}

function Field({ label, ...props }: { label: string; value: string; onChangeText: (value: string) => void; placeholder: string }) { return <View style={screen.field}><Text style={screen.fieldLabel}>{label}</Text><TextInput {...props} placeholderTextColor={Colors.muted} style={screen.input} /></View>; }
function Chip({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[screen.chip, selected && screen.chipActive]}><Text style={[screen.chipText, selected && screen.chipTextActive]}>{label}</Text></Pressable>; }

const screen = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.bg }, loadingText: { color: Colors.orange, fontFamily: Fonts.mono, fontSize: 10, letterSpacing: 2 }, page: { minHeight: '100%', padding: Spacing.xl }, top: { width: '100%', maxWidth: Layout.content, alignSelf: 'center', height: 56, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 30 }, brandLogo: { width: 34, height: 34, borderRadius: 5 }, brand: { color: Colors.text, fontFamily: Fonts.sans, fontSize: 15, fontWeight: '900', letterSpacing: 1.8 }, orange: { color: Colors.orange }, version: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, letterSpacing: 1, marginLeft: 'auto' },
  grid: { width: '100%', maxWidth: Layout.content, alignSelf: 'center', gap: 16 }, gridWide: { flexDirection: 'row', alignItems: 'stretch' }, hero: { flex: 0.82, minHeight: 660, backgroundColor: Colors.orange, padding: 36, justifyContent: 'space-between' }, heroTitle: { color: Colors.black, fontFamily: Fonts.sans, fontSize: 50, lineHeight: 53, fontWeight: '900', letterSpacing: -2 }, heroOutline: { color: Colors.orange, textShadowColor: Colors.black, textShadowOffset: { width: 1, height: 1 }, textShadowRadius: 1 }, heroCopy: { color: '#28120a', fontSize: 15, lineHeight: 23, marginTop: 20, maxWidth: 390 }, heroRule: { height: 1, backgroundColor: 'rgba(9,11,16,.25)', marginBottom: 22 }, heroMetrics: { flexDirection: 'row', justifyContent: 'space-between' }, heroNumber: { color: Colors.black, fontSize: 27, fontWeight: '900' }, heroLabel: { color: '#28120a', fontFamily: Fonts.mono, fontSize: 8, marginTop: 3, textTransform: 'uppercase' },
  builder: { flex: 1.3, minHeight: 660, padding: 28 }, steps: { flexDirection: 'row', marginBottom: 28 }, stepItem: { flex: 1, flexDirection: 'row', alignItems: 'center' }, stepDot: { width: 28, height: 28, borderWidth: 1, borderColor: Colors.lineStrong, alignItems: 'center', justifyContent: 'center' }, stepDotActive: { backgroundColor: Colors.orange, borderColor: Colors.orange }, stepDotText: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8 }, stepDotTextActive: { color: Colors.black, fontWeight: '900' }, stepLine: { flex: 1, height: 1, backgroundColor: Colors.line }, stepLineActive: { backgroundColor: Colors.orange }, help: { color: Colors.muted, fontSize: 12, lineHeight: 18, marginTop: 8, marginBottom: 20 },
  formGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, field: { width: '48%', flexGrow: 1, minWidth: 180 }, fieldLabel: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, fontWeight: '900', letterSpacing: 1, marginTop: 13, marginBottom: 7 }, input: { height: 44, backgroundColor: Colors.panelSoft, borderWidth: 1, borderColor: Colors.line, paddingHorizontal: 12, color: Colors.text, fontFamily: Fonts.sans, fontSize: 13, borderRadius: Radius.sm }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 }, chip: { borderWidth: 1, borderColor: Colors.line, backgroundColor: Colors.panelSoft, paddingHorizontal: 10, paddingVertical: 8, borderRadius: Radius.sm }, chipActive: { borderColor: Colors.orange, backgroundColor: Colors.orangeSoft }, chipText: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 9, fontWeight: '800' }, chipTextActive: { color: Colors.orange },
  roleGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, roleCard: { width: '23%', minWidth: 120, flexGrow: 1, minHeight: 105, padding: 10, borderWidth: 1, borderColor: Colors.line, backgroundColor: Colors.panelSoft }, roleCardActive: { borderColor: Colors.orange, backgroundColor: Colors.orangeSoft }, roleCode: { width: 30, height: 22, borderWidth: 1, borderColor: Colors.lineStrong, alignItems: 'center', justifyContent: 'center', marginBottom: 8 }, roleCodeActive: { backgroundColor: Colors.orange, borderColor: Colors.orange }, roleCodeText: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, fontWeight: '900' }, roleCodeTextActive: { color: Colors.black }, roleName: { color: Colors.text, fontSize: 11, fontWeight: '900' }, roleDescription: { color: Colors.muted, fontSize: 9, lineHeight: 13, marginTop: 4 },
  teamList: { gap: 8, paddingVertical: 18 }, teamCard: { width: 132, minHeight: 132, padding: 12, borderWidth: 1, borderColor: Colors.line, backgroundColor: Colors.panelSoft }, teamCardActive: { borderColor: Colors.orange, backgroundColor: Colors.orangeSoft }, teamName: { color: Colors.text, fontSize: 11, fontWeight: '900', marginTop: 10 }, teamMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, marginTop: 4 }, contractPreview: { padding: 14 }, contractHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 }, contractTeam: { color: Colors.text, fontSize: 15, fontWeight: '900' }, contractMeta: { color: Colors.muted, fontSize: 9, marginTop: 3 }, contractMetrics: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 16, gap: 12 }, contractLabel: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 7 }, contractValue: { color: Colors.text, fontSize: 12, fontWeight: '900', marginTop: 4 }, actions: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 'auto', paddingTop: 28 }, disclaimer: { width: '100%', maxWidth: Layout.content, alignSelf: 'center', color: '#4d5665', fontFamily: Fonts.mono, fontSize: 8, lineHeight: 13, marginTop: 18 },
});
