import { Href, router } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { useEffect, useMemo, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { Button, Eyebrow, Panel, Title } from '@/components/ui/game-ui';
import { RoundOneMark, TeamCrest } from '@/components/visual/game-marks';
import { Colors, Fonts, Layout, Radius, Spacing } from '@/constants/theme';
import { LOW_TIER_TEAMS, STARTER_TEAMS, TEAMS } from '@/data/teams';
import { TOURNAMENTS } from '@/data/tournaments';
import { useCareerStore } from '@/state/career-store';
import { PlayStyle, PlayerIdentity, PlayerRole, Region } from '@/types/game';
import { initialTeamOffers } from '@/engine/rosters';

const positions: { id: PlayerRole; code: string; name: string; description: string; style: PlayStyle }[] = [
  { id: 'Rifler', code: 'RIF', name: 'Fusilero', description: 'Posición flexible con rifle. Es la opción más simple para empezar.', style: 'Mechanical' },
  { id: 'Entry', code: 'ENT', name: 'Atacante', description: 'Entrás primero y buscás abrir la ronda.', style: 'Aggressive' },
  { id: 'AWPer', code: 'AWP', name: 'Francotirador', description: 'Jugás con AWP, paciencia y precisión.', style: 'Clutch' },
  { id: 'IGL', code: 'CAP', name: 'Capitán', description: 'Dirigís al equipo y tomás decisiones tácticas.', style: 'Tactical' },
];

export function CreateCareerScreen() {
  const { width } = useWindowDimensions(); const wide = width >= 900;
  const { career, hydrated, startCareer } = useCareerStore();
  const [step, setStep] = useState(1); const [nickname, setNickname] = useState(''); const [nationality, setNationality] = useState('Argentina'); const [age, setAge] = useState(17); const region: Region = 'Argentina'; const [role, setRole] = useState<PlayerRole>('Rifler'); const [teamId, setTeamId] = useState(STARTER_TEAMS[0]?.id ?? 'leo'); const [showAllTeams, setShowAllTeams] = useState(false);
  useEffect(() => { if (hydrated && career) router.replace('/game?view=dashboard' as Href); }, [career, hydrated]);
  const selectedPosition = positions.find((item) => item.id === role) ?? positions[0];
  const identityDraft = useMemo<PlayerIdentity>(() => ({ fullName: nickname.trim(), nickname: nickname.trim() || 'rookie', nationality, region, city: nationality === 'Argentina' ? 'Buenos Aires' : nationality, age, primaryLanguage: 'Español', secondaryLanguages: [], handedness: 'Diestro', personality: 'Competitivo', ambition: 82, riskTolerance: selectedPosition.style === 'Aggressive' ? 82 : 58, priority: 'Títulos', role, style: selectedPosition.style }), [age, nationality, nickname, region, role, selectedPosition.style]);
  const recommendedTeams = useMemo(() => initialTeamOffers(identityDraft), [identityDraft]);
  const teamChoices = showAllTeams ? LOW_TIER_TEAMS : recommendedTeams;
  const selectedTeam = useMemo(() => LOW_TIER_TEAMS.find((team) => team.id === teamId) ?? recommendedTeams[0] ?? STARTER_TEAMS[0], [recommendedTeams, teamId]);
  if (!hydrated || career) return <SafeAreaView style={screen.loading}><Text style={screen.loadingText}>ROUND/ONE · CARGANDO CARRERA</Text></SafeAreaView>;
  const canContinue = step !== 1 || nickname.trim().length >= 2;
  function launch() {
    const identity: PlayerIdentity = { ...identityDraft, nickname: nickname.trim(), fullName: nickname.trim() };
    startCareer(identity, selectedTeam.id);
  }
  return <SafeAreaView style={screen.safe}><ScrollView contentContainerStyle={screen.page} showsVerticalScrollIndicator={false}>
    <View style={screen.top}><RoundOneMark size={30} /><Text style={screen.brand}>ROUND<Text style={screen.orange}>/</Text>ONE</Text><View style={screen.topRule} /><Text style={screen.version}>{wide ? 'SIMULADOR DE CARRERA · BETA 1' : 'BETA 1'}</Text></View>
    <View style={[screen.grid, wide && screen.gridWide]}>
      <View style={screen.hero}><Image source={require('../../assets/phase2/major-cologne.webp')} resizeMode="cover" style={StyleSheet.absoluteFill} /><LinearGradient colors={['rgba(9,9,7,.15)', 'rgba(9,9,7,.72)', 'rgba(9,9,7,.98)']} locations={[0, 0.48, 1]} style={StyleSheet.absoluteFill} /><View style={screen.heroContent}><View><Eyebrow color={Colors.orange}>COUNTER-STRIKE · MODO CARRERA</Eyebrow><Text style={[screen.heroTitle, !wide && screen.heroTitleMobile]}>Tu nombre.{`\n`}Tu equipo.{`\n`}Tu <Text style={screen.heroAccent}>historia.</Text></Text><Text style={screen.heroCopy}>Creá tu jugador en tres pasos. Después la temporada avanza sola y se detiene cuando realmente tenés que decidir o competir.</Text></View><View><View style={screen.heroRule} /><View style={screen.heroMetrics}><View style={screen.heroMetric}><Text style={screen.heroNumber}>{TEAMS.length}</Text><Text style={screen.heroLabel}>clubes VRS</Text></View><View style={screen.heroMetric}><Text style={screen.heroNumber}>{TOURNAMENTS.length}</Text><Text style={screen.heroLabel}>eventos por año</Text></View><View style={screen.heroMetric}><Text style={screen.heroNumber}>12</Text><Text style={screen.heroLabel}>temporadas posibles</Text></View></View></View></View></View>
      <Panel style={screen.builder}>
        <View style={screen.steps}>{[1, 2, 3].map((value) => <View key={value} style={screen.stepItem}><View style={[screen.stepDot, step >= value && screen.stepDotActive]}><Text style={[screen.stepDotText, step >= value && screen.stepDotTextActive]}>0{value}</Text></View><View style={[screen.stepLine, step > value && screen.stepLineActive]} /></View>)}</View>
        {step === 1 ? <View><Eyebrow>01 · TU JUGADOR</Eyebrow><Title size="medium">Empezá por lo esencial</Title><Text style={screen.help}>Solo necesitás un apodo, una nacionalidad y una edad. El resto se construye jugando.</Text><View style={screen.formGrid}><Field label="APODO *" value={nickname} onChangeText={setNickname} placeholder="K1NG" /><Field label="NACIONALIDAD" value={nationality} onChangeText={setNationality} placeholder="Argentina" /></View><Text style={screen.fieldLabel}>EDAD INICIAL</Text><View style={screen.chips}>{[16, 17, 18, 19, 20].map((value) => <Chip key={value} label={String(value)} selected={age === value} onPress={() => setAge(value)} />)}</View></View> : null}
        {step === 2 ? <View><Eyebrow>02 · POSICIÓN</Eyebrow><Title size="medium">¿Cómo querés jugar?</Title><Text style={screen.help}>Elegí una de cuatro posiciones claras. Más adelante vas a poder desarrollar cualquier atributo.</Text><View style={screen.roleGrid}>{positions.map((item) => <Pressable accessibilityRole="button" accessibilityLabel={`Elegir ${item.name}`} key={item.id} onPress={() => setRole(item.id)} style={[screen.roleCard, role === item.id && screen.roleCardActive]}><View style={[screen.roleCode, role === item.id && screen.roleCodeActive]}><Text style={[screen.roleCodeText, role === item.id && screen.roleCodeTextActive]}>{item.code}</Text></View><Text style={screen.roleName}>{item.name}</Text><Text style={screen.roleDescription}>{item.description}</Text></Pressable>)}</View></View> : null}
        {step === 3 ? <View><Eyebrow>03 · PRIMER CONTRATO</Eyebrow><Title size="medium">Elegí dónde empezar</Title><Text style={screen.help}>Te mostramos tres clubes adecuados para debutar. También podés revisar todos los equipos de nivel bajo disponibles.</Text><View style={screen.offerToolbar}><Text style={screen.offerLabel}>{showAllTeams ? `${LOW_TIER_TEAMS.length} CLUBES DISPONIBLES` : '3 OFERTAS RECOMENDADAS'}</Text><Button compact variant="ghost" label={showAllTeams ? 'Ver recomendadas' : 'Ver todos'} onPress={() => { const next = !showAllTeams; setShowAllTeams(next); const choices = next ? LOW_TIER_TEAMS : recommendedTeams; if (!choices.some((team) => team.id === teamId)) setTeamId(choices[0]?.id ?? teamId); }} /></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={screen.teamList}>{teamChoices.map((team) => <Pressable accessibilityRole="button" accessibilityLabel={`Elegir ${team.name}`} key={team.id} onPress={() => setTeamId(team.id)} style={[screen.teamCard, teamId === team.id && screen.teamCardActive]}><TeamCrest id={team.id} color={team.color} size={50} /><Text style={screen.teamName}>{team.name}</Text><Text style={screen.teamMeta}>Puesto #{team.initialRanking} · {team.tier}</Text><Text style={screen.teamMeta}>{team.region} · {team.initialRanking > 150 ? 'más oportunidades de jugar' : 'mayor competencia interna'}</Text></Pressable>)}</ScrollView><Panel style={screen.contractPreview} accent="orange"><View style={screen.contractHeader}><TeamCrest id={selectedTeam.id} color={selectedTeam.color} /><View><Text style={screen.contractTeam}>{selectedTeam.name}</Text><Text style={screen.contractMeta}>{selectedTeam.city} · {selectedTeam.objective}</Text></View></View><View style={screen.contractMetrics}><View><Text style={screen.contractLabel}>SALARIO BASE</Text><Text style={screen.contractValue}>${Math.round(selectedTeam.averageSalary * 0.7).toLocaleString('en-US')}/mes</Text></View><View><Text style={screen.contractLabel}>LUGAR INICIAL</Text><Text style={screen.contractValue}>{selectedTeam.initialRanking > 150 ? 'TITULAR' : selectedTeam.initialRanking > 110 ? 'ROTACIÓN' : 'PROMESA'}</Text></View><View><Text style={screen.contractLabel}>MAPAS DEL EQUIPO</Text><Text style={screen.contractValue}>{selectedTeam.mapPool.length}</Text></View></View></Panel></View> : null}
        <View style={screen.actions}>{step > 1 ? <Button label="← Atrás" variant="ghost" onPress={() => setStep(step - 1)} /> : <View />}{step < 3 ? <Button label="Continuar →" disabled={!canContinue} onPress={() => { if (step === 2) setTeamId(recommendedTeams[0]?.id ?? teamId); setStep(step + 1); }} /> : <Button label="Firmar y empezar →" onPress={launch} />}</View>
      </Panel>
    </View>
    <Text style={screen.disclaimer}>Los rankings y rosters usan un snapshot público de Valve del 03/08/2026. Los valores financieros y de gestión son parámetros de simulación aproximados.</Text>
  </ScrollView></SafeAreaView>;
}

function Field({ label, ...props }: { label: string; value: string; onChangeText: (value: string) => void; placeholder: string }) { return <View style={screen.field}><Text style={screen.fieldLabel}>{label}</Text><TextInput {...props} placeholderTextColor={Colors.muted} style={screen.input} /></View>; }
function Chip({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[screen.chip, selected && screen.chipActive]}><Text style={[screen.chipText, selected && screen.chipTextActive]}>{label}</Text></Pressable>; }

const screen = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.bg }, loadingText: { color: Colors.orange, fontFamily: Fonts.mono, fontSize: 11, letterSpacing: 2 }, page: { minHeight: '100%', padding: Spacing.xl }, top: { width: '100%', maxWidth: Layout.content, alignSelf: 'center', height: 52, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 20, borderBottomWidth: 1, borderBottomColor: Colors.line }, brandLogo: { width: 30, height: 30, borderRadius: 2 }, brand: { color: Colors.text, fontFamily: Fonts.sans, fontSize: 14, fontWeight: '800', letterSpacing: 1.8 }, orange: { color: Colors.orange }, topRule: { width: 32, height: 1, backgroundColor: Colors.orange }, version: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 11, letterSpacing: 1, marginLeft: 'auto' },
  grid: { width: '100%', maxWidth: Layout.content, alignSelf: 'center', gap: 10 }, gridWide: { flexDirection: 'row', alignItems: 'stretch' }, hero: { flex: 0.88, minHeight: 680, overflow: 'hidden', borderWidth: 1, borderColor: Colors.line }, heroContent: { flex: 1, padding: 36, justifyContent: 'space-between' }, heroTitle: { color: Colors.text, fontFamily: Fonts.sans, fontSize: 50, lineHeight: 51, fontWeight: '800', letterSpacing: -2.1 }, heroTitleMobile: { fontSize: 42, lineHeight: 44 }, heroAccent: { color: Colors.orange }, heroCopy: { color: Colors.textSoft, fontSize: 14, lineHeight: 22, marginTop: 20, maxWidth: 420 }, heroRule: { height: 1, backgroundColor: Colors.lineStrong, marginBottom: 16 }, heroMetrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, heroMetric: { minWidth: 112, flexGrow: 1, borderTopWidth: 2, borderTopColor: Colors.orange, backgroundColor: 'rgba(9,9,7,.72)', padding: 11 }, heroNumber: { color: Colors.text, fontSize: 24, fontWeight: '800' }, heroLabel: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 11, marginTop: 4, textTransform: 'uppercase', letterSpacing: 0.7 },
  builder: { flex: 1.3, minHeight: 680, padding: 28, borderTopWidth: 2, borderTopColor: Colors.orange, backgroundColor: Colors.bgRaised }, steps: { flexDirection: 'row', marginBottom: 28 }, stepItem: { flex: 1, flexDirection: 'row', alignItems: 'center' }, stepDot: { width: 28, height: 28, borderWidth: 1, borderColor: Colors.lineStrong, alignItems: 'center', justifyContent: 'center' }, stepDotActive: { backgroundColor: Colors.text, borderColor: Colors.text }, stepDotText: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 10 }, stepDotTextActive: { color: Colors.black, fontWeight: '900' }, stepLine: { flex: 1, height: 1, backgroundColor: Colors.line }, stepLineActive: { backgroundColor: Colors.orange }, help: { color: Colors.muted, fontSize: 12, lineHeight: 18, marginTop: 8, marginBottom: 20 },
  formGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, field: { width: '48%', flexGrow: 1, minWidth: 180 }, fieldLabel: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 11, fontWeight: '900', letterSpacing: 1, marginTop: 13, marginBottom: 7 }, input: { height: 44, backgroundColor: Colors.bg, borderWidth: 1, borderColor: Colors.line, paddingHorizontal: 12, color: Colors.text, fontFamily: Fonts.sans, fontSize: 14, borderRadius: Radius.sm }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 }, chip: { borderWidth: 1, borderColor: Colors.line, backgroundColor: Colors.bg, paddingHorizontal: 10, paddingVertical: 8, borderRadius: Radius.sm }, chipActive: { borderColor: Colors.orange, backgroundColor: Colors.orangeSoft }, chipText: { color: Colors.muted, fontFamily: Fonts.sans, fontSize: 12, fontWeight: '800' }, chipTextActive: { color: Colors.orange },
  roleGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, roleCard: { width: '23%', minWidth: 120, flexGrow: 1, minHeight: 105, padding: 10, borderWidth: 1, borderColor: Colors.line, backgroundColor: Colors.bg }, roleCardActive: { borderColor: Colors.orange, backgroundColor: Colors.orangeSoft }, roleCode: { width: 30, height: 22, borderWidth: 1, borderColor: Colors.lineStrong, alignItems: 'center', justifyContent: 'center', marginBottom: 8 }, roleCodeActive: { backgroundColor: Colors.text, borderColor: Colors.text }, roleCodeText: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 10, fontWeight: '900' }, roleCodeTextActive: { color: Colors.black }, roleName: { color: Colors.text, fontSize: 15, fontWeight: '800' }, roleDescription: { color: Colors.textSoft, fontSize: 12, lineHeight: 17, marginTop: 4 },
  offerToolbar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 }, offerLabel: { color: Colors.orange, fontFamily: Fonts.mono, fontSize: 10, fontWeight: '900', letterSpacing: 1 }, teamList: { gap: 8, paddingVertical: 18 }, teamCard: { width: 148, minHeight: 150, padding: 12, borderWidth: 1, borderColor: Colors.line, backgroundColor: Colors.bg }, teamCardActive: { borderColor: Colors.orange, backgroundColor: Colors.orangeSoft }, teamName: { color: Colors.text, fontSize: 13, fontWeight: '800', marginTop: 10 }, teamMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 10, marginTop: 4 }, contractPreview: { padding: 14, backgroundColor: Colors.bg }, contractHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 }, contractTeam: { color: Colors.text, fontSize: 15, fontWeight: '800' }, contractMeta: { color: Colors.textSoft, fontSize: 12, marginTop: 3 }, contractMetrics: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 16, gap: 12 }, contractLabel: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 10 }, contractValue: { color: Colors.text, fontSize: 12, fontWeight: '800', marginTop: 4 }, actions: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 'auto', paddingTop: 28 }, disclaimer: { width: '100%', maxWidth: Layout.content, alignSelf: 'center', color: Colors.muted, fontFamily: Fonts.mono, fontSize: 10, lineHeight: 13, marginTop: 18 },
});
