import { Href, router } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { useEffect, useMemo, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { Button, Eyebrow, Panel, Title } from '@/components/ui/game-ui';
import { RoundOneMark, TeamCrest } from '@/components/visual/game-marks';
import { Colors, Fonts, Layout, Radius, Spacing } from '@/constants/theme';
import { LOW_TIER_TEAMS, STARTER_TEAMS, TEAMS } from '@/data/teams';
import { TOURNAMENTS } from '@/data/tournaments';
import { useCareerStore } from '@/state/career-store';
import { Personality, PlayStyle, PlayerIdentity, PlayerRole, Region } from '@/types/game';
import { initialTeamOffers } from '@/engine/rosters';

const roles: { id: PlayerRole; code: string; description: string }[] = [
  { id: 'Entry', code: 'ENT', description: 'Abrís sites y tomás el primer duelo.' }, { id: 'AWPer', code: 'AWP', description: 'Precisión, paciencia y rondas decisivas.' }, { id: 'Rifler', code: 'RIF', description: 'Consistencia mecánica en todos los mapas.' }, { id: 'Lurker', code: 'LUR', description: 'Leés rotaciones y castigás espacios.' }, { id: 'Support', code: 'SUP', description: 'Utility, trades y estructura colectiva.' }, { id: 'IGL', code: 'IGL', description: 'Liderazgo y lectura táctica.' }, { id: 'Hybrid', code: 'HYB', description: 'Adaptación entre rifle y AWP.' }, { id: 'Anchor', code: 'ANC', description: 'Defensa estable y sangre fría.' },
];
const stylesList: PlayStyle[] = ['Aggressive', 'Tactical', 'Clutch', 'Mechanical', 'Team player', 'Star player', 'Utility specialist', 'Defensive', 'Flexible'];
const personalities: Personality[] = ['Ambicioso', 'Disciplinado', 'Carismático', 'Reservado', 'Competitivo', 'Analítico'];

export function CreateCareerScreen() {
  const { width } = useWindowDimensions(); const wide = width >= 900;
  const { career, hydrated, startCareer } = useCareerStore();
  const [step, setStep] = useState(1); const [fullName, setFullName] = useState(''); const [nickname, setNickname] = useState(''); const [city, setCity] = useState('Buenos Aires'); const [nationality, setNationality] = useState('Argentina'); const [age, setAge] = useState(17); const region: Region = 'Argentina'; const [role, setRole] = useState<PlayerRole>('Rifler'); const [playStyle, setPlayStyle] = useState<PlayStyle>('Mechanical'); const [personality, setPersonality] = useState<Personality>('Competitivo'); const [priority, setPriority] = useState<PlayerIdentity['priority']>('Títulos'); const [teamId, setTeamId] = useState(STARTER_TEAMS[0]?.id ?? 'leo'); const [showAllTeams, setShowAllTeams] = useState(false);
  useEffect(() => { if (hydrated && career) router.replace('/game?view=dashboard' as Href); }, [career, hydrated]);
  const identityDraft = useMemo<PlayerIdentity>(() => ({ fullName: fullName.trim() || nickname.trim(), nickname: nickname.trim() || 'rookie', nationality, region, city, age, primaryLanguage: 'Español', secondaryLanguages: ['Inglés'], handedness: 'Diestro', personality, ambition: 82, riskTolerance: playStyle === 'Aggressive' ? 82 : 58, priority, role, style: playStyle }), [age, city, fullName, nationality, nickname, personality, playStyle, priority, role]);
  const recommendedTeams = useMemo(() => initialTeamOffers(identityDraft), [identityDraft]);
  const teamChoices = showAllTeams ? LOW_TIER_TEAMS : recommendedTeams;
  const selectedTeam = useMemo(() => LOW_TIER_TEAMS.find((team) => team.id === teamId) ?? recommendedTeams[0] ?? STARTER_TEAMS[0], [recommendedTeams, teamId]);
  if (!hydrated || career) return <SafeAreaView style={screen.loading}><Text style={screen.loadingText}>ROUND/ONE · LOADING CAREER</Text></SafeAreaView>;
  const canContinue = step !== 1 || nickname.trim().length >= 2;
  function launch() {
    const identity: PlayerIdentity = { ...identityDraft, nickname: nickname.trim(), fullName: fullName.trim() || nickname.trim() };
    startCareer(identity, selectedTeam.id);
  }
  return <SafeAreaView style={screen.safe}><ScrollView contentContainerStyle={screen.page} showsVerticalScrollIndicator={false}>
    <View style={screen.top}><RoundOneMark size={30} /><Text style={screen.brand}>ROUND<Text style={screen.orange}>/</Text>ONE</Text><View style={screen.topRule} /><Text style={screen.version}>{wide ? 'CAREER SIMULATOR · BETA 1' : 'BETA 1'}</Text></View>
    <View style={[screen.grid, wide && screen.gridWide]}>
      <View style={screen.hero}><Image source={require('../../assets/phase2/major-cologne.webp')} resizeMode="cover" style={StyleSheet.absoluteFill} /><LinearGradient colors={['rgba(9,9,7,.15)', 'rgba(9,9,7,.72)', 'rgba(9,9,7,.98)']} locations={[0, 0.48, 1]} style={StyleSheet.absoluteFill} /><View style={screen.heroContent}><View><Eyebrow color={Colors.orange}>COUNTER-STRIKE · CAREER MODE</Eyebrow><Text style={[screen.heroTitle, !wide && screen.heroTitleMobile]}>Tu nombre.{`\n`}Tu equipo.{`\n`}Tu <Text style={screen.heroAccent}>historia.</Text></Text><Text style={screen.heroCopy}>Una carrera deportiva con contexto, riesgo y memoria. Las decisiones cambian tu lugar en el roster; los resultados nunca están escritos.</Text></View><View><View style={screen.heroRule} /><View style={screen.heroMetrics}><View style={screen.heroMetric}><Text style={screen.heroNumber}>{TEAMS.length}</Text><Text style={screen.heroLabel}>clubes VRS</Text></View><View style={screen.heroMetric}><Text style={screen.heroNumber}>{TOURNAMENTS.length}</Text><Text style={screen.heroLabel}>eventos por año</Text></View><View style={screen.heroMetric}><Text style={screen.heroNumber}>12</Text><Text style={screen.heroLabel}>temporadas posibles</Text></View></View></View></View></View>
      <Panel style={screen.builder}>
        <View style={screen.steps}>{[1, 2, 3].map((value) => <View key={value} style={screen.stepItem}><View style={[screen.stepDot, step >= value && screen.stepDotActive]}><Text style={[screen.stepDotText, step >= value && screen.stepDotTextActive]}>0{value}</Text></View><View style={[screen.stepLine, step > value && screen.stepLineActive]} /></View>)}</View>
        {step === 1 ? <View><Eyebrow>01 · IDENTIDAD</Eyebrow><Title size="medium">Creá tu player</Title><Text style={screen.help}>Tu origen afecta idiomas, mercado inicial y eventos regionales.</Text><View style={screen.formGrid}><Field label="NICKNAME *" value={nickname} onChangeText={setNickname} placeholder="K1NG" /><Field label="NOMBRE" value={fullName} onChangeText={setFullName} placeholder="Nombre completo" /><Field label="CIUDAD" value={city} onChangeText={setCity} placeholder="Buenos Aires" /><Field label="NACIONALIDAD" value={nationality} onChangeText={setNationality} placeholder="Argentina" /></View><Text style={screen.fieldLabel}>EDAD INICIAL</Text><View style={screen.chips}>{[15, 16, 17, 18, 19, 20, 21, 22].map((value) => <Chip key={value} label={String(value)} selected={age === value} onPress={() => setAge(value)} />)}</View><Text style={screen.fieldLabel}>PERSONALIDAD</Text><View style={screen.chips}>{personalities.map((value) => <Chip key={value} label={value} selected={personality === value} onPress={() => setPersonality(value)} />)}</View></View> : null}
        {step === 2 ? <View><Eyebrow>02 · IDENTIDAD COMPETITIVA</Eyebrow><Title size="medium">Definí tu juego</Title><Text style={screen.help}>Los bonuses iniciales son distintos y cada atributo entra en la simulación.</Text><View style={screen.roleGrid}>{roles.map((item) => <Pressable key={item.id} onPress={() => setRole(item.id)} style={[screen.roleCard, role === item.id && screen.roleCardActive]}><View style={[screen.roleCode, role === item.id && screen.roleCodeActive]}><Text style={[screen.roleCodeText, role === item.id && screen.roleCodeTextActive]}>{item.code}</Text></View><Text style={screen.roleName}>{item.id}</Text><Text style={screen.roleDescription}>{item.description}</Text></Pressable>)}</View><Text style={screen.fieldLabel}>ESTILO</Text><View style={screen.chips}>{stylesList.map((value) => <Chip key={value} label={value} selected={playStyle === value} onPress={() => setPlayStyle(value)} />)}</View><Text style={screen.fieldLabel}>PRIORIDAD DE CARRERA</Text><View style={screen.chips}>{(['Estabilidad', 'Dinero', 'Títulos', 'Minutos'] as const).map((value) => <Chip key={value} label={value} selected={priority === value} onPress={() => setPriority(value)} />)}</View></View> : null}
        {step === 3 ? <View><Eyebrow>03 · PRIMER CONTRATO</Eyebrow><Title size="medium">Tres ofertas, una carrera</Title><Text style={screen.help}>Las identidades oficiales están guardadas localmente. Las propuestas equilibran ranking, región y minutos; también podés explorar todos los clubes desde el puesto 80.</Text><View style={screen.offerToolbar}><Text style={screen.offerLabel}>{showAllTeams ? `${LOW_TIER_TEAMS.length} CLUBES DISPONIBLES` : '3 OFERTAS RECOMENDADAS'}</Text><Button compact variant="ghost" label={showAllTeams ? 'Ver recomendadas' : 'Explorar todos'} onPress={() => { const next = !showAllTeams; setShowAllTeams(next); const choices = next ? LOW_TIER_TEAMS : recommendedTeams; if (!choices.some((team) => team.id === teamId)) setTeamId(choices[0]?.id ?? teamId); }} /></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={screen.teamList}>{teamChoices.map((team) => <Pressable key={team.id} onPress={() => setTeamId(team.id)} style={[screen.teamCard, teamId === team.id && screen.teamCardActive]}><TeamCrest id={team.id} color={team.color} size={50} /><Text style={screen.teamName}>{team.name}</Text><Text style={screen.teamMeta}>#{team.initialRanking} · {team.tier}</Text><Text style={screen.teamMeta}>{team.region} · {team.initialRanking > 150 ? 'minutos altos' : 'competencia interna'}</Text></Pressable>)}</ScrollView><Panel style={screen.contractPreview} accent="orange"><View style={screen.contractHeader}><TeamCrest id={selectedTeam.id} color={selectedTeam.color} /><View><Text style={screen.contractTeam}>{selectedTeam.name}</Text><Text style={screen.contractMeta}>{selectedTeam.city} · {selectedTeam.objective}</Text></View></View><View style={screen.contractMetrics}><View><Text style={screen.contractLabel}>SALARIO BASE</Text><Text style={screen.contractValue}>${Math.round(selectedTeam.averageSalary * 0.7).toLocaleString('en-US')}/mes</Text></View><View><Text style={screen.contractLabel}>ROL INICIAL</Text><Text style={screen.contractValue}>{selectedTeam.initialRanking > 150 ? 'STARTER' : selectedTeam.initialRanking > 110 ? 'ROTATION' : 'PROSPECT'}</Text></View><View><Text style={screen.contractLabel}>MAP POOL</Text><Text style={screen.contractValue}>{selectedTeam.mapPool.length}</Text></View></View></Panel></View> : null}
        <View style={screen.actions}>{step > 1 ? <Button label="← Atrás" variant="ghost" onPress={() => setStep(step - 1)} /> : <View />}{step < 3 ? <Button label="Continuar →" disabled={!canContinue} onPress={() => { if (step === 2) setTeamId(recommendedTeams[0]?.id ?? teamId); setStep(step + 1); }} /> : <Button label="Firmar y empezar →" onPress={launch} />}</View>
      </Panel>
    </View>
    <Text style={screen.disclaimer}>Los rankings y rosters usan un snapshot público de Valve del 03/08/2026. Los valores financieros y de gestión son parámetros de simulación aproximados.</Text>
  </ScrollView></SafeAreaView>;
}

function Field({ label, ...props }: { label: string; value: string; onChangeText: (value: string) => void; placeholder: string }) { return <View style={screen.field}><Text style={screen.fieldLabel}>{label}</Text><TextInput {...props} placeholderTextColor={Colors.muted} style={screen.input} /></View>; }
function Chip({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[screen.chip, selected && screen.chipActive]}><Text style={[screen.chipText, selected && screen.chipTextActive]}>{label}</Text></Pressable>; }

const screen = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.bg }, loadingText: { color: Colors.orange, fontFamily: Fonts.mono, fontSize: 10, letterSpacing: 2 }, page: { minHeight: '100%', padding: Spacing.xl }, top: { width: '100%', maxWidth: Layout.content, alignSelf: 'center', height: 52, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 20, borderBottomWidth: 1, borderBottomColor: Colors.line }, brandLogo: { width: 30, height: 30, borderRadius: 2 }, brand: { color: Colors.text, fontFamily: Fonts.sans, fontSize: 14, fontWeight: '800', letterSpacing: 1.8 }, orange: { color: Colors.orange }, topRule: { width: 32, height: 1, backgroundColor: Colors.orange }, version: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, letterSpacing: 1, marginLeft: 'auto' },
  grid: { width: '100%', maxWidth: Layout.content, alignSelf: 'center', gap: 10 }, gridWide: { flexDirection: 'row', alignItems: 'stretch' }, hero: { flex: 0.88, minHeight: 680, overflow: 'hidden', borderWidth: 1, borderColor: Colors.line }, heroContent: { flex: 1, padding: 36, justifyContent: 'space-between' }, heroTitle: { color: Colors.text, fontFamily: Fonts.sans, fontSize: 50, lineHeight: 51, fontWeight: '800', letterSpacing: -2.1 }, heroTitleMobile: { fontSize: 42, lineHeight: 44 }, heroAccent: { color: Colors.orange }, heroCopy: { color: Colors.textSoft, fontSize: 14, lineHeight: 22, marginTop: 20, maxWidth: 420 }, heroRule: { height: 1, backgroundColor: Colors.lineStrong, marginBottom: 16 }, heroMetrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, heroMetric: { minWidth: 112, flexGrow: 1, borderTopWidth: 2, borderTopColor: Colors.orange, backgroundColor: 'rgba(9,9,7,.72)', padding: 11 }, heroNumber: { color: Colors.text, fontSize: 24, fontWeight: '800' }, heroLabel: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 7, marginTop: 4, textTransform: 'uppercase', letterSpacing: 0.7 },
  builder: { flex: 1.3, minHeight: 680, padding: 28, borderTopWidth: 2, borderTopColor: Colors.orange, backgroundColor: Colors.bgRaised }, steps: { flexDirection: 'row', marginBottom: 28 }, stepItem: { flex: 1, flexDirection: 'row', alignItems: 'center' }, stepDot: { width: 28, height: 28, borderWidth: 1, borderColor: Colors.lineStrong, alignItems: 'center', justifyContent: 'center' }, stepDotActive: { backgroundColor: Colors.text, borderColor: Colors.text }, stepDotText: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8 }, stepDotTextActive: { color: Colors.black, fontWeight: '900' }, stepLine: { flex: 1, height: 1, backgroundColor: Colors.line }, stepLineActive: { backgroundColor: Colors.orange }, help: { color: Colors.muted, fontSize: 12, lineHeight: 18, marginTop: 8, marginBottom: 20 },
  formGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, field: { width: '48%', flexGrow: 1, minWidth: 180 }, fieldLabel: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, fontWeight: '900', letterSpacing: 1, marginTop: 13, marginBottom: 7 }, input: { height: 44, backgroundColor: Colors.bg, borderWidth: 1, borderColor: Colors.line, paddingHorizontal: 12, color: Colors.text, fontFamily: Fonts.sans, fontSize: 13, borderRadius: Radius.sm }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 }, chip: { borderWidth: 1, borderColor: Colors.line, backgroundColor: Colors.bg, paddingHorizontal: 10, paddingVertical: 8, borderRadius: Radius.sm }, chipActive: { borderColor: Colors.orange, backgroundColor: Colors.orangeSoft }, chipText: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 9, fontWeight: '800' }, chipTextActive: { color: Colors.orange },
  roleGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, roleCard: { width: '23%', minWidth: 120, flexGrow: 1, minHeight: 105, padding: 10, borderWidth: 1, borderColor: Colors.line, backgroundColor: Colors.bg }, roleCardActive: { borderColor: Colors.orange, backgroundColor: Colors.orangeSoft }, roleCode: { width: 30, height: 22, borderWidth: 1, borderColor: Colors.lineStrong, alignItems: 'center', justifyContent: 'center', marginBottom: 8 }, roleCodeActive: { backgroundColor: Colors.text, borderColor: Colors.text }, roleCodeText: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, fontWeight: '900' }, roleCodeTextActive: { color: Colors.black }, roleName: { color: Colors.text, fontSize: 11, fontWeight: '800' }, roleDescription: { color: Colors.muted, fontSize: 9, lineHeight: 13, marginTop: 4 },
  offerToolbar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 }, offerLabel: { color: Colors.orange, fontFamily: Fonts.mono, fontSize: 8, fontWeight: '900', letterSpacing: 1 }, teamList: { gap: 8, paddingVertical: 18 }, teamCard: { width: 148, minHeight: 150, padding: 12, borderWidth: 1, borderColor: Colors.line, backgroundColor: Colors.bg }, teamCardActive: { borderColor: Colors.orange, backgroundColor: Colors.orangeSoft }, teamName: { color: Colors.text, fontSize: 11, fontWeight: '800', marginTop: 10 }, teamMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, marginTop: 4 }, contractPreview: { padding: 14, backgroundColor: Colors.bg }, contractHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 }, contractTeam: { color: Colors.text, fontSize: 15, fontWeight: '800' }, contractMeta: { color: Colors.muted, fontSize: 9, marginTop: 3 }, contractMetrics: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 16, gap: 12 }, contractLabel: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 7 }, contractValue: { color: Colors.text, fontSize: 12, fontWeight: '800', marginTop: 4 }, actions: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 'auto', paddingTop: 28 }, disclaimer: { width: '100%', maxWidth: Layout.content, alignSelf: 'center', color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, lineHeight: 13, marginTop: 18 },
});
