import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View, useWindowDimensions } from 'react-native';

import { Badge, Button, Divider, Eyebrow, Metric, Panel, ProgressBar, SectionHeader, StatRow, Title } from '@/components/ui/game-ui';
import { Colors, Fonts } from '@/constants/theme';
import { ATTRIBUTE_LABELS } from '@/data/roles';
import { getTeam } from '@/data/teams';
import { getCareerEvent } from '@/data/events';
import { useCareerStore } from '@/state/career-store';
import { AttributeKey } from '@/types/game';
import { overallRating, xpForLevel } from '@/engine/progression';
import { playerWorldRank } from '@/engine/ranking';
import { PlayerAvatar } from '@/components/visual/game-marks';

const go = (screen: string) => router.push({ pathname: '/[screen]', params: { screen } });

export function DashboardView() {
  const { career, advance } = useCareerStore(); const { width } = useWindowDimensions();
  if (!career) return null; const team = getTeam(career.teamId); const wide = width >= 850;
  const rank = career.rankings.find((entry) => entry.teamId === team.id)?.rank ?? team.initialRanking;
  const activeMajor = career.majorCampaigns.find((item) => item.id === career.activeMajorId);
  const latest = career.matches[career.matches.length - 1]; const pending = career.offseasonPending ? 'Off-season pendiente' : career.pendingMinigame ? 'Minijuego pendiente' : activeMajor ? `Major · ${activeMajor.stage.replaceAll('-', ' ')}` : career.pendingMatchId ? 'Partido pendiente' : career.pendingDecisionId ? 'Decisión pendiente' : 'Semana lista';
  return <View><View style={view.heroRow}><View><Eyebrow>TEMPORADA {career.season} · {career.year}</Eyebrow><Title>Bienvenido, <Text style={view.orange}>{career.player.identity.nickname}</Text></Title><Text style={view.subtitle}>Semana {career.week} · Mes {career.month} · {team.name}</Text></View><View style={view.heroActions}><Badge tone={career.finished ? 'purple' : career.player.form >= 60 ? 'green' : 'orange'}>{career.finished ? 'Carrera finalizada' : pending}</Badge>{!career.finished ? <Button label="Avanzar semana →" disabled={Boolean(career.pendingDecisionId || career.pendingMatchId)} onPress={advance} /> : <Button label="Ver resumen →" onPress={() => go('summary')} />}</View></View>
    <View style={view.metricGrid}><Panel style={view.metricPanel}><Metric label="Overall" value={overallRating(career.player.attributes)} tone="orange" detail={`${career.player.identity.role} · ${career.player.identity.style}`} /></Panel><Panel style={view.metricPanel}><Metric label="Ranking equipo" value={`#${rank}`} detail={`${team.vrsPoints} VRS base`} /></Panel><Panel style={view.metricPanel}><Metric label="Ranking jugador" value={`#${playerWorldRank(career)}`} tone="green" detail="Proyección global" /></Panel><Panel style={view.metricPanel}><Metric label="Valor de mercado" value={`$${Math.round(career.player.marketValue / 1000)}K`} detail={`$${career.contract.monthlySalary}/mes`} /></Panel></View>
    <View style={[view.columns, wide && view.columnsWide]}><View style={view.mainColumn}>
      <SectionHeader eyebrow="PRÓXIMA ACCIÓN" title={pending} />
      {career.offseasonPending ? <ActionCard tone="orange" eyebrow="OFF-SEASON OBLIGATORIO" title="Balance & Upgrades" copy="Revisá la temporada, tus finanzas y compras antes de iniciar el próximo año." button="Abrir Season Review" onPress={() => go('season-review')} /> : career.pendingMinigame ? <ActionCard tone="orange" eyebrow="DECISIÓN INTERACTIVA" title="Minijuego pendiente" copy="La campaña está pausada y guardada hasta resolver esta decisión clave." button="Ir al minijuego" onPress={() => go('minigames')} /> : activeMajor ? <ActionCard tone="red" eyebrow="MAJOR CAMPAIGN" title={activeMajor.stage.replaceAll('-', ' ')} copy="Continuá tu camino por clasificatorios, Swiss y playoffs." button="Abrir Major Hub" onPress={() => go('major-hub')} /> : career.pendingMatchId ? <ActionCard tone="red" eyebrow="MATCH DAY" title="La serie está lista" copy="Elegí el plan táctico y resolvé el próximo partido." button="Ir al partido" onPress={() => go('match')} /> : career.pendingDecisionId ? <ActionCard tone="orange" eyebrow="DECISIÓN DE CARRERA" title={getCareerEvent(career.pendingDecisionId)?.title ?? 'Tu decisión importa'} copy={getCareerEvent(career.pendingDecisionId)?.description ?? ''} button="Tomar decisión" onPress={() => go('decision')} /> : <ActionCard tone="green" eyebrow="CALENDARIO" title="Prepará la próxima semana" copy="Podés entrenar, revisar el calendario o avanzar cuando estés listo." button="Entrenar" onPress={() => go('training')} />}
      <SectionHeader eyebrow="ÚLTIMO RESULTADO" title={latest ? `${latest.won ? 'Victoria' : 'Derrota'} ${latest.seriesScore}` : 'Todavía no debutaste'} action={latest ? <Button compact variant="ghost" label="Detalle" onPress={() => go('match')} /> : undefined} />
      <Panel>{latest ? <View><View style={view.resultTop}><Badge tone={latest.won ? 'green' : 'red'}>{latest.won ? 'WIN' : 'LOSS'}</Badge><Text style={view.resultRating}>{latest.aggregate.rating.toFixed(2)} <Text style={view.mutedSmall}>RATING</Text></Text></View><View style={view.metricGridInner}><Metric label="Kills" value={latest.aggregate.kills} /><Metric label="ADR" value={latest.aggregate.adr} /><Metric label="KAST" value={`${latest.aggregate.kast}%`} /><Metric label="Clutches" value={latest.aggregate.clutches} /></View></View> : <Text style={view.empty}>Avanzá el calendario para disputar tu primera serie profesional.</Text>}</Panel>
      <SectionHeader eyebrow="CAREER FEED" title="Últimas noticias" /><Panel>{career.news.slice(0, 5).map((item, index) => <View key={`${item}-${index}`} style={view.feedRow}><Text style={view.feedIndex}>{String(index + 1).padStart(2, '0')}</Text><Text style={view.feedText}>{item}</Text></View>)}</Panel>
    </View><View style={view.sideColumn}><PlayerSnapshot /><SectionHeader eyebrow="TEMPORADA" title="Progreso anual" /><Panel><View style={view.seasonHeader}><Text style={view.seasonWeek}>MES {career.month} · SEMANA {career.week}</Text><Text style={view.seasonPercent}>{Math.round(((career.month - 1) * 4 + career.week) / 48 * 100)}%</Text></View><ProgressBar value={((career.month - 1) * 4 + career.week) / 48 * 100} /><Divider /><StatRow label="Forma" value={career.player.form} color={Colors.green} /><StatRow label="Confianza" value={career.player.attributes.confidence} color={Colors.blue} /><StatRow label="Química" value={career.chemistry} color={Colors.purple} /><StatRow label="Fatiga" value={career.player.fatigue} color={career.player.fatigue > 70 ? Colors.red : Colors.orange} /></Panel></View></View>
  </View>;
}

function ActionCard({ eyebrow, title, copy, button, tone, onPress }: { eyebrow: string; title: string; copy: string; button: string; tone: 'red' | 'orange' | 'green'; onPress: () => void }) { return <Panel accent={tone} style={view.actionCard}><View style={view.actionCopy}><Eyebrow color={tone === 'red' ? Colors.red : tone === 'green' ? Colors.green : Colors.orange}>{eyebrow}</Eyebrow><Text style={view.actionTitle}>{title}</Text><Text style={view.actionDescription}>{copy}</Text></View><Button label={`${button} →`} onPress={onPress} /></Panel>; }

function PlayerSnapshot() {
  const { career } = useCareerStore(); if (!career) return null; const team = getTeam(career.teamId);
  return <Panel style={view.snapshot}><View style={view.snapshotTop}><PlayerAvatar id={career.visualAssets.avatarId} color={team.color} size={52} /><View style={view.snapshotCopy}><Text style={view.snapshotNick}>{career.player.identity.nickname}</Text><Text style={view.snapshotMeta}>{career.player.identity.age} años · {career.player.identity.nationality}</Text></View><Text style={view.snapshotOverall}>{overallRating(career.player.attributes)}</Text></View><Divider /><StatRow label="Aim" value={career.player.attributes.aim} color={Colors.orange} /><StatRow label="Game sense" value={career.player.attributes.gameSense} color={Colors.blue} /><StatRow label="Mental" value={career.player.attributes.mentalStrength} color={Colors.green} /><StatRow label="Comunicación" value={career.player.attributes.communication} color={Colors.purple} /><View style={view.levelRow}><Text style={view.levelText}>NIVEL {career.player.level}</Text><Text style={view.levelText}>{career.player.xp}/{xpForLevel(career.player.level)} XP</Text></View><ProgressBar value={career.player.xp / xpForLevel(career.player.level) * 100} /></Panel>;
}

export function ProfileView() {
  const { career, setAvatar } = useCareerStore(); if (!career) return null; const team = getTeam(career.teamId); const attributeEntries = Object.entries(career.player.attributes) as [AttributeKey, number][];
  const groups: { title: string; keys: AttributeKey[]; color: string }[] = [{ title: 'Mecánicas', keys: ['aim', 'crosshairPlacement', 'sprayControl', 'movement', 'reaction', 'awpSkill', 'pistolSkill'], color: Colors.orange }, { title: 'Impacto', keys: ['entryImpact', 'tradeEfficiency', 'clutch', 'positioning', 'consistency'], color: Colors.red }, { title: 'Utility y táctica', keys: ['utilityUsage', 'flashAssists', 'smokeLineups', 'grenadeTiming', 'gameSense', 'mapKnowledge', 'readingOpponents'], color: Colors.blue }, { title: 'Mental y equipo', keys: ['communication', 'leadership', 'discipline', 'adaptability', 'mentalStrength', 'confidence', 'stamina', 'mediaSkill', 'englishCommunication', 'teamChemistry'], color: Colors.green }];
  return <View><SectionHeader eyebrow="PLAYER PROFILE" title={career.player.identity.nickname} /><Panel style={view.profileHero}><View style={view.profileIdentity}><PlayerAvatar id={career.visualAssets.avatarId} color={team.color} size={72} /><View><Text style={view.profileName}>{career.player.identity.fullName}</Text><Text style={view.profileMeta}>{career.player.identity.role} · {career.player.identity.style} · {career.player.identity.personality}</Text><View style={view.badges}><Badge tone="orange">{career.player.identity.nationality}</Badge><Badge>{career.player.identity.handedness}</Badge><Badge tone="green">Nivel {career.player.level}</Badge></View><View style={view.badges}>{['avatar-01', 'avatar-02', 'avatar-03', 'avatar-04'].map((id) => <Button key={id} compact variant={career.visualAssets.avatarId === id ? 'primary' : 'ghost'} label={id.slice(-2)} onPress={() => setAvatar(id)} />)}</View></View></View><View style={view.overallBlock}><Text style={view.overallLarge}>{overallRating(career.player.attributes)}</Text><Text style={view.overallLabel}>OVERALL</Text></View></Panel>
    <View style={view.attributeGrid}>{groups.map((group) => <Panel key={group.title} style={view.attributePanel}><SectionHeader title={group.title} />{attributeEntries.filter(([key]) => group.keys.includes(key)).map(([key, value]) => <StatRow key={key} label={ATTRIBUTE_LABELS[key]} value={value} color={group.color} />)}</Panel>)}</View>
  </View>;
}

export function TimelineView() {
  const { career } = useCareerStore(); if (!career) return null;
  const entries = [...career.matches.map((match) => ({ season: match.season, label: `${match.won ? 'Victoria' : 'Derrota'} ${match.seriesScore}`, detail: `${match.aggregate.rating.toFixed(2)} rating · ${match.aggregate.kills} kills`, tone: match.won ? 'green' as const : 'red' as const })), ...career.decisions.map((decision) => ({ season: decision.season, label: getCareerEvent(decision.eventId)?.title ?? 'Decisión', detail: decision.outcome, tone: 'orange' as const })), ...career.trophies.map((trophy) => ({ season: trophy.season, label: trophy.name, detail: trophy.mvp ? 'Campeón y MVP' : 'Campeón', tone: 'purple' as const }))].sort((a, b) => b.season - a.season);
  return <View><SectionHeader eyebrow="CAREER TIMELINE" title="La historia, decisión por decisión" /><Panel>{entries.length ? entries.map((entry, index) => <View key={`${entry.label}-${index}`} style={view.timelineRow}><View style={view.timelineRail}><View style={view.timelineDot} />{index < entries.length - 1 ? <View style={view.timelineLine} /> : null}</View><View style={view.timelineContent}><View style={view.timelineHeader}><Badge tone={entry.tone}>S{entry.season}</Badge><Text style={view.timelineTitle}>{entry.label}</Text></View><Text style={view.timelineDetail}>{entry.detail}</Text></View></View>) : <Text style={view.empty}>Tu timeline se va a completar con partidos, decisiones, contratos y títulos.</Text>}</Panel></View>;
}

export function DecisionView() {
  const { career, choose } = useCareerStore(); if (!career) return null; const event = getCareerEvent(career.pendingDecisionId);
  if (!event) return <View><SectionHeader eyebrow="DECISION ENGINE" title="No hay una decisión pendiente" /><ActionCard tone="green" eyebrow="TODO EN ORDEN" title="Seguí construyendo tu carrera" copy="Volvé al dashboard y avanzá una semana para encontrar nuevos eventos." button="Ir al dashboard" onPress={() => go('dashboard')} /></View>;
  return <View><SectionHeader eyebrow={`${event.category.toUpperCase()} · TEMPORADA ${career.season}`} title="Tu próxima decisión" /><Panel accent="orange" style={view.decisionHero}><Badge tone="orange">DECISIÓN CON MEMORIA</Badge><Text style={view.decisionTitle}>{event.title}</Text><Text style={view.decisionCopy}>{event.description}</Text></Panel><Text style={view.question}>¿QUÉ HACÉS?</Text><View style={view.choiceGrid}>{event.choices.map((choice, index) => <Pressable key={choice.id} onPress={() => choose(choice)} style={({ pressed }) => [view.choice, choice.risk === 'high' && view.choiceRisk, pressed && view.choicePressed]}><View style={view.choiceTop}><Text style={view.choiceIndex}>0{index + 1}</Text><Badge tone={choice.risk === 'high' ? 'red' : choice.risk === 'medium' ? 'orange' : 'green'}>{choice.risk} risk</Badge></View><Text style={view.choiceTitle}>{choice.title}</Text><Text style={view.choiceDescription}>{choice.description}</Text><Text style={view.choiceEffect}>{choice.effectPreview}</Text><Text style={view.choiceArrow}>↗</Text></Pressable>)}</View></View>;
}

export function CalendarView() {
  const { career, advance } = useCareerStore(); if (!career) return null;
  const current = career.month * 10 + career.week;
  return <View><SectionHeader eyebrow={`TEMPORADA ${career.season} · ${career.year}`} title="Calendario competitivo" action={<Button compact label="Avanzar semana" disabled={Boolean(career.pendingDecisionId || career.pendingMatchId)} onPress={advance} />} /><View style={view.monthGrid}>{Array.from({ length: 12 }, (_, index) => index + 1).map((month) => { const events = career.calendar.filter((event) => event.month === month && event.kind !== 'scrim'); return <Panel key={month} style={[view.monthCard, month === career.month && view.monthCardActive]}><View style={view.monthHeader}><Text style={view.monthNumber}>{String(month).padStart(2, '0')}</Text><Badge tone={month === career.month ? 'orange' : current > month * 10 + 4 ? 'green' : 'neutral'}>{month === career.month ? 'actual' : current > month * 10 + 4 ? 'cerrado' : 'próximo'}</Badge></View>{events.slice(0, 4).map((event) => <View key={event.id} style={view.calendarEvent}><View style={[view.calendarDot, event.kind === 'major' && view.majorDot]} /><View style={view.calendarCopy}><Text style={view.calendarTitle} numberOfLines={1}>S{event.week} · {event.title}</Text><Text style={view.calendarKind}>{event.kind}</Text></View></View>)}{events.length === 0 ? <Text style={view.emptySmall}>Scrims y preparación</Text> : null}</Panel>; })}</View></View>;
}

const view = StyleSheet.create({
  heroRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'flex-end', gap: 18, marginBottom: 24 }, orange: { color: Colors.orange }, subtitle: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 10, marginTop: 9, textTransform: 'uppercase', letterSpacing: 0.8 }, heroActions: { flexDirection: 'row', alignItems: 'center', gap: 9, flexWrap: 'wrap' },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 26 }, metricPanel: { minWidth: 160, flexGrow: 1, flexBasis: 180 }, columns: { gap: 22 }, columnsWide: { flexDirection: 'row' }, mainColumn: { flex: 1.65, gap: 8 }, sideColumn: { flex: 0.75, minWidth: 270, gap: 8 }, actionCard: { flexDirection: 'row', alignItems: 'center', gap: 18, marginBottom: 24 }, actionCopy: { flex: 1 }, actionTitle: { color: Colors.text, fontSize: 20, fontWeight: '900' }, actionDescription: { color: Colors.muted, fontSize: 12, lineHeight: 18, marginTop: 5 }, resultTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, resultRating: { color: Colors.orange, fontSize: 26, fontWeight: '900' }, mutedSmall: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8 }, metricGridInner: { flexDirection: 'row', flexWrap: 'wrap', gap: 18, marginTop: 20 }, empty: { color: Colors.muted, fontSize: 12, lineHeight: 18 }, feedRow: { flexDirection: 'row', gap: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: Colors.line }, feedIndex: { color: Colors.orange, fontFamily: Fonts.mono, fontSize: 9 }, feedText: { color: Colors.textSoft, fontSize: 11, lineHeight: 17, flex: 1 }, snapshot: { marginBottom: 20 }, snapshotTop: { flexDirection: 'row', alignItems: 'center' }, snapshotCopy: { flex: 1, marginLeft: 12 }, snapshotNick: { color: Colors.text, fontSize: 17, fontWeight: '900' }, snapshotMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, marginTop: 4 }, snapshotOverall: { color: Colors.orange, fontSize: 30, fontWeight: '900' }, levelRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8, marginBottom: 6 }, levelText: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, fontWeight: '800' }, seasonHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 9 }, seasonWeek: { color: Colors.textSoft, fontFamily: Fonts.mono, fontSize: 9, fontWeight: '800' }, seasonPercent: { color: Colors.orange, fontFamily: Fonts.mono, fontSize: 9 },
  profileHero: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: 20, marginBottom: 18 }, profileIdentity: { flexDirection: 'row', alignItems: 'center', gap: 16 }, profileName: { color: Colors.text, fontSize: 24, fontWeight: '900' }, profileMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 9, marginTop: 5 }, badges: { flexDirection: 'row', gap: 5, marginTop: 11, flexWrap: 'wrap' }, overallBlock: { alignItems: 'flex-end' }, overallLarge: { color: Colors.orange, fontSize: 52, fontWeight: '900' }, overallLabel: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, letterSpacing: 1 }, attributeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, attributePanel: { flex: 1, minWidth: 250 },
  timelineRow: { flexDirection: 'row', minHeight: 74 }, timelineRail: { width: 24, alignItems: 'center' }, timelineDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: Colors.orange, borderWidth: 2, borderColor: Colors.orangeSoft }, timelineLine: { width: 1, flex: 1, backgroundColor: Colors.line }, timelineContent: { flex: 1, paddingBottom: 18 }, timelineHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 }, timelineTitle: { color: Colors.text, fontSize: 13, fontWeight: '900' }, timelineDetail: { color: Colors.muted, fontSize: 10, lineHeight: 15, marginTop: 6 },
  decisionHero: { padding: 28, marginBottom: 20 }, decisionTitle: { color: Colors.text, fontSize: 34, lineHeight: 38, fontWeight: '900', letterSpacing: -1, marginTop: 14 }, decisionCopy: { color: Colors.textSoft, fontSize: 14, lineHeight: 22, marginTop: 12, maxWidth: 780 }, question: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 9, fontWeight: '900', letterSpacing: 1.3, marginBottom: 10 }, choiceGrid: { gap: 9 }, choice: { backgroundColor: Colors.panel, borderWidth: 1, borderColor: Colors.line, padding: 17, minHeight: 132 }, choiceRisk: { borderColor: '#49262b' }, choicePressed: { borderColor: Colors.orange, backgroundColor: Colors.orangeSoft }, choiceTop: { flexDirection: 'row', justifyContent: 'space-between' }, choiceIndex: { color: Colors.orange, fontFamily: Fonts.mono, fontSize: 10, fontWeight: '900' }, choiceTitle: { color: Colors.text, fontSize: 15, fontWeight: '900', marginTop: 10 }, choiceDescription: { color: Colors.muted, fontSize: 11, lineHeight: 17, marginTop: 5 }, choiceEffect: { color: Colors.green, fontFamily: Fonts.mono, fontSize: 8, fontWeight: '800', textTransform: 'uppercase', marginTop: 12 }, choiceArrow: { position: 'absolute', right: 17, bottom: 14, color: Colors.muted, fontSize: 18 },
  monthGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, monthCard: { minWidth: 220, flex: 1, flexBasis: 245, minHeight: 190 }, monthCardActive: { borderColor: Colors.orange }, monthHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 }, monthNumber: { color: Colors.text, fontFamily: Fonts.mono, fontSize: 22, fontWeight: '900' }, calendarEvent: { flexDirection: 'row', gap: 9, marginBottom: 11 }, calendarDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: Colors.blue, marginTop: 4 }, majorDot: { backgroundColor: Colors.orange }, calendarCopy: { flex: 1 }, calendarTitle: { color: Colors.textSoft, fontSize: 10, fontWeight: '800' }, calendarKind: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 7, textTransform: 'uppercase', marginTop: 3 }, emptySmall: { color: Colors.muted, fontSize: 9 },
});
