import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { Badge, Button, Divider, Eyebrow, Metric, Panel, SectionHeader } from '@/components/ui/game-ui';
import { TeamCrest } from '@/components/visual/game-marks';
import { Colors, Fonts } from '@/constants/theme';
import { getMap } from '@/data/maps';
import { getTeam } from '@/data/teams';
import { getTournament, MAJORS, TOURNAMENTS } from '@/data/tournaments';
import { playerWorldRank } from '@/engine/ranking';
import { useCareerStore } from '@/state/career-store';

export function TournamentView() {
  const { career } = useCareerStore(); const [filter, setFilter] = useState<'all' | 'major' | 'S' | 'regional'>('all');
  if (!career) return null;
  const list = TOURNAMENTS.filter((item) => filter === 'all' || filter === 'major' && item.kind === 'major' || filter === 'S' && item.tier === 'S' || filter === 'regional' && ['regional', 'academy'].includes(item.kind));
  return <View><SectionHeader eyebrow="GLOBAL CIRCUIT" title="Torneos de la temporada" /><View style={c.filters}>{(['all', 'major', 'S', 'regional'] as const).map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={[c.filter, filter === item && c.filterActive]}><Text style={[c.filterText, filter === item && c.filterTextActive]}>{item.toUpperCase()}</Text></Pressable>)}</View><View style={c.tournamentGrid}>{list.map((tournament) => { const played = career.matches.filter((match) => match.tournamentId === tournament.id); const wins = played.filter((match) => match.won).length; const campaign = career.tournamentCampaigns.find((item) => item.tournamentId === tournament.id && item.season === career.season); return <Panel key={tournament.id} style={[c.tournamentCard, tournament.kind === 'major' && c.majorCard]}><View style={c.tournamentTop}><Badge tone={campaign ? campaign.finish === 'Campeón' ? 'green' : campaign.status === 'missed' ? 'red' : 'orange' : tournament.kind === 'major' ? 'orange' : tournament.tier === 'S' ? 'purple' : 'neutral'}>{campaign?.finish ?? (tournament.kind === 'major' ? 'MAJOR' : `${tournament.tier}-TIER`)}</Badge><Text style={c.tournamentDate}>M{String(tournament.month).padStart(2, '0')} · S{tournament.week}</Text></View><Text style={c.tournamentName}>{tournament.name}</Text><Text style={c.tournamentLocation}>{tournament.location}</Text><Divider /><View style={c.tournamentMetrics}><Metric label="Prize pool" value={`$${tournament.prizePool >= 1000000 ? `${tournament.prizePool / 1000000}M` : `${tournament.prizePool / 1000}K`}`} /><Metric label="Equipos" value={tournament.teams} /><Metric label="Formato" value={tournament.format} /></View><View style={c.tournamentFooter}><Text style={c.tournamentPlayed}>{campaign ? `${campaign.wins}-${campaign.losses} · ${campaign.playerRating.toFixed(2)} · ${campaign.narrative}` : played.length ? `${wins}-${played.length - wins} en tu carrera` : tournament.qualification}</Text><Text style={c.points}>+{tournament.rankingPoints} pts</Text></View></Panel>; })}</View></View>;
}

export function MatchView() {
  const { career, resolveMatch } = useCareerStore(); const [approach, setApproach] = useState<'aggressive' | 'balanced' | 'save'>('balanced');
  if (!career) return null; const team = getTeam(career.teamId); const latest = career.matches[career.matches.length - 1];
  if (career.pendingMatchId) {
    const [tournamentId, opponentId] = career.pendingMatchId.split('|'); const tournament = getTournament(tournamentId); const opponent = getTeam(opponentId);
    return <View><SectionHeader eyebrow={`${tournament.shortName} · MATCH DAY`} title={`${team.name} vs ${opponent.name}`} /><Panel accent="orange" style={c.versus}><View style={c.versusTeam}><TeamCrest id={team.id} color={team.color} size={76} /><Text style={c.versusName}>{team.name}</Text><Text style={c.versusRank}>#{career.rankings.find((entry) => entry.teamId === team.id)?.rank}</Text></View><View style={c.versusMiddle}><Badge tone="orange">{tournament.seriesFormat}</Badge><Text style={c.vs}>VS</Text><Text style={c.versusMeta}>{tournament.location}</Text></View><View style={c.versusTeam}><TeamCrest id={opponent.id} color={opponent.color} size={76} /><Text style={c.versusName}>{opponent.name}</Text><Text style={c.versusRank}>#{opponent.initialRanking}</Text></View></Panel>
      <SectionHeader eyebrow="TACTICAL MINIGAME" title="Elegí el plan de la serie" /><View style={c.tactics}>{[{ id: 'aggressive' as const, title: 'Buscar el primer duelo', copy: '+Entry impact · +fatiga · -disciplina', tone: 'red' as const }, { id: 'balanced' as const, title: 'Jugar por protocolos', copy: 'Rendimiento estable y riesgo controlado', tone: 'green' as const }, { id: 'save' as const, title: 'Economía y late rounds', copy: '+disciplina · -impacto inicial', tone: 'blue' as const }].map((tactic) => <Pressable key={tactic.id} onPress={() => setApproach(tactic.id)} style={[c.tactic, approach === tactic.id && c.tacticActive]}><Badge tone={tactic.tone}>{tactic.id}</Badge><Text style={c.tacticTitle}>{tactic.title}</Text><Text style={c.tacticCopy}>{tactic.copy}</Text></Pressable>)}</View><Button label="Simular serie →" onPress={() => resolveMatch(approach)} />
      <SectionHeader eyebrow="MAP POOL" title="Posibles mapas" /><View style={c.mapRow}>{tournament.mapPool.map((mapId) => <Panel key={mapId} style={c.mapChip}><Text style={c.mapName}>{getMap(mapId).name}</Text><Text style={c.mapMeta}>CT {getMap(mapId).ctBias > 2 ? 'favored' : 'balanced'}</Text></Panel>)}</View></View>;
  }
  return <View><SectionHeader eyebrow="MATCH CENTER" title={latest ? 'Última serie' : 'Sin partidos todavía'} />{latest ? <MatchReport match={latest} /> : <Panel><Text style={c.empty}>Avanzá el calendario desde el dashboard para generar tu próximo encuentro.</Text></Panel>}</View>;
}

function MatchReport({ match }: { match: NonNullable<ReturnType<typeof useCareerStore>['career']>['matches'][number] }) {
  const opponent = getTeam(match.opponentTeamId); const tournament = getTournament(match.tournamentId);
  return <View><Panel accent={match.won ? 'green' : 'red'}><View style={c.reportHeader}><View><Badge tone={match.won ? 'green' : 'red'}>{match.won ? 'VICTORY' : 'DEFEAT'}</Badge><Text style={c.reportTitle}>{match.seriesScore} vs {opponent.name}</Text><Text style={c.reportMeta}>{tournament.name} · Temporada {match.season}</Text></View><Text style={c.reportRating}>{match.aggregate.rating.toFixed(2)}<Text style={c.reportRatingLabel}> RATING</Text></Text></View><View style={c.reportMetrics}><Metric label="Kills / Deaths" value={`${match.aggregate.kills} / ${match.aggregate.deaths}`} /><Metric label="ADR" value={match.aggregate.adr} /><Metric label="KAST" value={`${match.aggregate.kast}%`} /><Metric label="Opening" value={`${match.aggregate.openingKills}-${match.aggregate.openingDeaths}`} /><Metric label="HS" value={`${match.aggregate.headshotPercentage}%`} /><Metric label="Clutches" value={match.aggregate.clutches} /></View></Panel><SectionHeader eyebrow="MAP BY MAP" title="Serie completa" /><View style={c.maps}>{match.maps.map((map) => <Panel key={map.mapId} style={c.mapResult}><View style={c.mapResultTop}><Text style={c.mapResultName}>{getMap(map.mapId).name}</Text><Text style={[c.mapScore, map.teamScore > map.opponentScore ? c.winText : c.lossText]}>{map.teamScore}:{map.opponentScore}</Text></View><Text style={c.mapResultStats}>{map.playerStats.kills}-{map.playerStats.deaths} · {map.playerStats.adr} ADR · {map.playerStats.rating.toFixed(2)}</Text>{map.overtime ? <Badge tone="orange">OVERTIME</Badge> : null}</Panel>)}</View><SectionHeader eyebrow="POR QUÉ PASÓ" title="Factores de simulación" /><Panel>{match.explanation.map((item, index) => <View key={item} style={c.explainRow}><Text style={c.explainIndex}>0{index + 1}</Text><Text style={c.explainText}>{item}</Text></View>)}</Panel></View>;
}

export function StatisticsView() {
  const { career } = useCareerStore(); if (!career) return null; const matches = career.matches;
  const total = (key: 'kills' | 'deaths' | 'assists' | 'clutches' | 'openingKills' | 'flashAssists' | 'utilityDamage') => matches.reduce((sum, match) => sum + match.aggregate[key], 0);
  const avg = (key: 'rating' | 'adr' | 'kast' | 'headshotPercentage' | 'ctRating' | 'tRating' | 'pistolRating' | 'pressureRating') => matches.reduce((sum, match) => sum + match.aggregate[key], 0) / Math.max(1, matches.length);
  const wins = matches.filter((match) => match.won).length;
  return <View><SectionHeader eyebrow="PLAYER ANALYTICS" title="Estadísticas de carrera" /><View style={c.statsHero}><Panel style={c.primaryStat}><Eyebrow>CAREER RATING</Eyebrow><Text style={c.statHeroValue}>{avg('rating').toFixed(2)}</Text><Text style={c.statHeroMeta}>{matches.length} series · {wins} victorias · {matches.length - wins} derrotas</Text></Panel><View style={c.statsGrid}><Panel><Metric label="K/D" value={(total('kills') / Math.max(1, total('deaths'))).toFixed(2)} tone="orange" /></Panel><Panel><Metric label="ADR" value={avg('adr').toFixed(1)} /></Panel><Panel><Metric label="KAST" value={`${avg('kast').toFixed(1)}%`} /></Panel><Panel><Metric label="Win rate" value={`${(wins / Math.max(1, matches.length) * 100).toFixed(0)}%`} tone="green" /></Panel></View></View>
    <SectionHeader eyebrow="DETAILED DATA" title="Impacto acumulado" /><View style={c.detailGrid}>{[['Kills', total('kills')], ['Deaths', total('deaths')], ['Assists', total('assists')], ['Opening kills', total('openingKills')], ['Clutches', total('clutches')], ['Flash assists', total('flashAssists')], ['Utility damage', total('utilityDamage')], ['HS%', `${avg('headshotPercentage').toFixed(1)}%`], ['CT rating', avg('ctRating').toFixed(2)], ['T rating', avg('tRating').toFixed(2)], ['Pistol rating', avg('pistolRating').toFixed(2)], ['Pressure rating', avg('pressureRating').toFixed(2)]].map(([label, value]) => <Panel key={String(label)} style={c.detailStat}><Metric label={String(label)} value={value} /></Panel>)}</View>
    <SectionHeader eyebrow="MATCH LOG" title="Forma reciente" /><ScrollView horizontal showsHorizontalScrollIndicator={false}><View style={c.table}><View style={c.tableRow}><Text style={[c.cell, c.cellWide, c.head]}>RIVAL</Text><Text style={[c.cell, c.head]}>RES</Text><Text style={[c.cell, c.head]}>K-D</Text><Text style={[c.cell, c.head]}>ADR</Text><Text style={[c.cell, c.head]}>KAST</Text><Text style={[c.cell, c.head]}>RATING</Text></View>{matches.slice().reverse().slice(0, 20).map((match) => <View key={match.id} style={c.tableRow}><Text style={[c.cell, c.cellWide]}>{getTeam(match.opponentTeamId).name}</Text><Text style={[c.cell, match.won ? c.winText : c.lossText]}>{match.won ? 'W' : 'L'} {match.seriesScore}</Text><Text style={c.cell}>{match.aggregate.kills}-{match.aggregate.deaths}</Text><Text style={c.cell}>{match.aggregate.adr}</Text><Text style={c.cell}>{match.aggregate.kast}%</Text><Text style={[c.cell, match.aggregate.rating >= 1.1 && c.winText]}>{match.aggregate.rating.toFixed(2)}</Text></View>)}</View></ScrollView></View>;
}

export function RankingsView() {
  const { career } = useCareerStore(); const [region, setRegion] = useState('Global'); if (!career) return null;
  const ranking = career.rankings.map((entry) => ({ ...entry, team: getTeam(entry.teamId) })).filter((entry) => region === 'Global' || entry.team.region === region).slice(0, 100);
  return <View><SectionHeader eyebrow="VALVE REGIONAL STANDINGS" title="Ranking mundial" /><View style={c.rankHero}><Panel accent="orange"><Eyebrow>PLAYER WORLD RANK</Eyebrow><Text style={c.playerRank}>#{playerWorldRank(career)}</Text><Text style={c.playerRankMeta}>{career.player.identity.role} · Proyección dinámica</Text></Panel><Panel><Eyebrow>MAJORS DE LA TEMPORADA</Eyebrow><View style={c.majorList}>{MAJORS.map((major) => <View key={major.id}><Text style={c.majorName}>{major.name}</Text><Text style={c.majorMeta}>M{major.month} · {major.location}</Text></View>)}</View></Panel></View><View style={c.filters}>{['Global', 'Europe', 'CIS', 'Argentina', 'Brazil', 'North America', 'Asia', 'Oceania'].map((item) => <Pressable key={item} onPress={() => setRegion(item)} style={[c.filter, region === item && c.filterActive]}><Text style={[c.filterText, region === item && c.filterTextActive]}>{item}</Text></Pressable>)}</View><Panel>{ranking.map((entry, index) => <View key={entry.teamId} style={[c.rankingRow, entry.teamId === career.teamId && c.rankingActive]}><Text style={c.rankNumber}>{String(index + 1).padStart(2, '0')}</Text><TeamCrest id={entry.team.id} color={entry.team.color} size={32} /><View style={c.rankCopy}><Text style={c.rankTeam}>{entry.team.name}</Text><Text style={c.rankMeta}>{entry.team.region} · {entry.team.tier}</Text></View><Text style={[c.trend, entry.trend > 0 ? c.winText : entry.trend < 0 ? c.lossText : undefined]}>{entry.trend > 0 ? `↑${entry.trend}` : entry.trend < 0 ? `↓${Math.abs(entry.trend)}` : '—'}</Text><Text style={c.rankPoints}>{entry.points} pts</Text></View>)}</Panel></View>;
}

const c = StyleSheet.create({
  filters: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 18 }, filter: { paddingHorizontal: 11, paddingVertical: 8, borderWidth: 1, borderColor: Colors.line, backgroundColor: Colors.panelSoft }, filterActive: { borderColor: Colors.orange, backgroundColor: Colors.orangeSoft }, filterText: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, fontWeight: '900' }, filterTextActive: { color: Colors.orange }, tournamentGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, tournamentCard: { minWidth: 270, flexGrow: 1, flexBasis: 330 }, majorCard: { borderColor: Colors.orange }, tournamentTop: { flexDirection: 'row', justifyContent: 'space-between' }, tournamentDate: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8 }, tournamentName: { color: Colors.text, fontSize: 17, fontWeight: '900', marginTop: 15 }, tournamentLocation: { color: Colors.muted, fontSize: 10, marginTop: 5 }, tournamentMetrics: { flexDirection: 'row', gap: 13 }, tournamentFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginTop: 18 }, tournamentPlayed: { color: Colors.muted, fontSize: 9, lineHeight: 13, flex: 1 }, points: { color: Colors.green, fontFamily: Fonts.mono, fontSize: 9, marginLeft: 10 },
  versus: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', padding: 30, marginBottom: 25 }, versusTeam: { flex: 1, alignItems: 'center', gap: 8 }, versusName: { color: Colors.text, fontSize: 16, fontWeight: '900', textAlign: 'center' }, versusRank: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 9 }, versusMiddle: { alignItems: 'center', paddingHorizontal: 16 }, vs: { color: Colors.orange, fontSize: 25, fontWeight: '900', marginVertical: 12 }, versusMeta: { color: Colors.muted, fontSize: 8, maxWidth: 110, textAlign: 'center' }, tactics: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginBottom: 16 }, tactic: { minWidth: 210, flex: 1, padding: 16, backgroundColor: Colors.panel, borderWidth: 1, borderColor: Colors.line }, tacticActive: { borderColor: Colors.orange, backgroundColor: Colors.orangeSoft }, tacticTitle: { color: Colors.text, fontSize: 13, fontWeight: '900', marginTop: 12 }, tacticCopy: { color: Colors.muted, fontSize: 9, lineHeight: 14, marginTop: 5 }, mapRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, mapChip: { minWidth: 120, flex: 1 }, mapName: { color: Colors.text, fontSize: 11, fontWeight: '900' }, mapMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 7, marginTop: 4 }, empty: { color: Colors.muted, fontSize: 12 },
  reportHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', flexWrap: 'wrap', gap: 15 }, reportTitle: { color: Colors.text, fontSize: 28, fontWeight: '900', marginTop: 12 }, reportMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 9, marginTop: 5 }, reportRating: { color: Colors.orange, fontSize: 42, fontWeight: '900' }, reportRatingLabel: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8 }, reportMetrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 17, marginTop: 25 }, maps: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, mapResult: { minWidth: 220, flex: 1 }, mapResultTop: { flexDirection: 'row', justifyContent: 'space-between' }, mapResultName: { color: Colors.text, fontSize: 13, fontWeight: '900' }, mapScore: { fontSize: 18, fontWeight: '900' }, mapResultStats: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, marginVertical: 10 }, explainRow: { flexDirection: 'row', paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: Colors.line }, explainIndex: { width: 34, color: Colors.orange, fontFamily: Fonts.mono, fontSize: 9 }, explainText: { color: Colors.textSoft, fontSize: 11 },
  statsHero: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 25 }, primaryStat: { minWidth: 250, flex: 0.8 }, statHeroValue: { color: Colors.orange, fontSize: 68, lineHeight: 72, fontWeight: '900' }, statHeroMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8 }, statsGrid: { flex: 2, minWidth: 300, flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, detailGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 25 }, detailStat: { minWidth: 135, flexGrow: 1, flexBasis: 150 }, table: { minWidth: 720 }, tableRow: { flexDirection: 'row', minHeight: 42, alignItems: 'center', borderBottomWidth: 1, borderBottomColor: Colors.line }, cell: { width: 95, color: Colors.textSoft, fontFamily: Fonts.mono, fontSize: 9 }, cellWide: { width: 190 }, head: { color: Colors.muted, fontSize: 8, fontWeight: '900' }, winText: { color: Colors.green }, lossText: { color: Colors.red },
  rankHero: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 18 }, playerRank: { color: Colors.orange, fontSize: 60, fontWeight: '900' }, playerRankMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8 }, majorList: { flexDirection: 'row', gap: 25, flexWrap: 'wrap' }, majorName: { color: Colors.text, fontSize: 13, fontWeight: '900' }, majorMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, marginTop: 4 }, rankingRow: { minHeight: 51, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 8, borderBottomWidth: 1, borderBottomColor: Colors.line }, rankingActive: { backgroundColor: Colors.orangeSoft, borderLeftWidth: 2, borderLeftColor: Colors.orange }, rankNumber: { width: 28, color: Colors.muted, fontFamily: Fonts.mono, fontSize: 10 }, rankCopy: { flex: 1 }, rankTeam: { color: Colors.text, fontSize: 11, fontWeight: '900' }, rankMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 7, marginTop: 3 }, trend: { width: 35, color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8 }, rankPoints: { width: 72, textAlign: 'right', color: Colors.textSoft, fontFamily: Fonts.mono, fontSize: 9 },
});
