import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { Badge, Button, Divider, Eyebrow, Metric, Panel, ProgressBar, SectionHeader, StatRow } from '@/components/ui/game-ui';
import { TeamCrest } from '@/components/visual/game-marks';
import { Colors, Fonts } from '@/constants/theme';
import { ATTRIBUTE_LABELS } from '@/data/roles';
import { getTeam } from '@/data/teams';
import { PRO_PLAYER_POOL } from '@/data/pro-players';
import { TRAINING_ACTIVITIES } from '@/data/training';
import { contractNegotiationAvailability, contractValue } from '@/engine/contracts';
import { roleFit, transferOffers } from '@/engine/rosters';
import { overallRating, trainingAvailability } from '@/engine/progression';
import { useCareerStore } from '@/state/career-store';

export function LegacyTeamView() {
  const { career } = useCareerStore(); if (!career) return null; const team = getTeam(career.teamId);
  return <View><SectionHeader eyebrow="ORGANIZACIÓN ACTUAL" title={team.name} /><Panel accent="orange" style={o.teamHero}><TeamCrest id={team.id} color={team.color} size={88} /><View style={o.teamHeroCopy}><View style={o.badges}><Badge tone="orange">#{career.rankings.find((entry) => entry.teamId === team.id)?.rank} VRS</Badge><Badge tone="purple">{team.tier}</Badge><Badge>{team.region}</Badge></View><Text style={o.teamName}>{team.name}</Text><Text style={o.teamMeta}>{team.city}, {team.country} · {team.culture}</Text><Text style={o.objective}>Objetivo: {team.objective}</Text></View></Panel><View style={o.metricGrid}><Panel><Metric label="Tu puesto" value={career.squad.role.toUpperCase()} tone="orange" detail={`${career.squad.mapShare}% de mapas`} /></Panel><Panel><Metric label="Seguridad del rol" value={career.squad.roleSecurity} tone={career.squad.roleSecurity >= 65 ? 'green' : 'red'} /></Panel><Panel><Metric label="Confianza coach" value={career.squad.coachTrust} /></Panel><Panel><Metric label="Competencia interna" value={career.squad.internalCompetition} detail={career.squad.competitorName} /></Panel><Panel><Metric label="Química" value={career.chemistry} tone={career.chemistry >= 70 ? 'green' : 'neutral'} /></Panel><Panel><Metric label="Presupuesto" value={`$${(team.budget / 1000000).toFixed(1)}M`} /></Panel></View><Panel accent={career.squad.role === 'benched' ? 'red' : 'orange'}><Eyebrow>ROSTER STATUS</Eyebrow><Text style={o.objective}>{career.squad.lastChangeReason}</Text></Panel><View style={o.twoColumns}><Panel style={o.flex}><SectionHeader eyebrow="IDENTIDAD" title="Estilo competitivo" /><StatRow label="Agresividad" value={team.aggression} color={Colors.red} /><StatRow label="Staff" value={team.staffQuality} color={Colors.blue} /><StatRow label="Sponsor" value={team.sponsorLevel} color={Colors.green} /><StatRow label="Actividad de mercado" value={team.transferActivity} color={Colors.orange} /><Divider /><Text style={o.description}>{team.tacticalStyle}. La organización prioriza una cultura {team.culture.toLowerCase()}.</Text></Panel><Panel style={o.flex}><SectionHeader eyebrow="MAP POOL" title="Mapas preferidos" />{team.mapPool.map((map, index) => <View key={map} style={o.mapRow}><Text style={o.mapRank}>0{index + 1}</Text><Text style={o.mapName}>{map.toUpperCase()}</Text><ProgressBar value={Math.max(52, 88 - index * 7)} color={index < 2 ? Colors.orange : Colors.blue} /></View>)}</Panel></View></View>;
}

/* export function TeamView() {
  const { career } = useCareerStore(); if (!career) return null; const team = getTeam(career.teamId); const liveRank = career.rankings.find((entry) => entry.teamId === team.id)?.rank ?? team.initialRanking;
  const mapRows = team.mapPool.map((mapId) => { const samples = career.matches.flatMap((match) => match.maps.filter((map) => map.mapId === mapId)); return { mapId, samples, winRate: samples.length ? samples.filter((item) => item.teamScore > item.opponentScore).length / samples.length * 100 : 0, rating: samples.length ? samples.reduce((sum, item) => sum + item.playerStats.rating, 0) / samples.length : 0 }; });
  return <View><SectionHeader eyebrow="ORGANIZACIÓN ACTUAL" title={team.name} /><Panel accent="orange" style={o.teamHero}><TeamCrest id={team.id} color={team.color} size={88} /><View style={o.teamHeroCopy}><View style={o.badges}><Badge tone="orange">#{liveRank} VRS</Badge><Badge tone="purple">{team.tier}</Badge><Badge>{team.region}</Badge></View><Text style={o.teamName}>{team.name}</Text><Text style={o.teamMeta}>{team.city}, {team.country} · {team.culture}</Text><Text style={o.objective">Objetivo: {team.objective}</Text></View></Panel><View style={o.metricGrid}><Panel><Metric label="Ranking VRS actual" value={`#${liveRank}`} tone="orange" detail={`trend ${career.rankings.find((entry) => entry.teamId === team.id)?.trend ?? 0}`} /></Panel><Panel><Metric label="Forma del equipo" value={career.matches.filter((item) => item.won).slice(-5).length} detail="victorias en las últimas 5" /></Panel><Panel><Metric label="Química" value={career.chemistry} /></Panel><Panel><Metric label="Presupuesto" value={`$${(team.budget / 1000000).toFixed(1)}M`} /></Panel></View><Panel><SectionHeader eyebrow="MAPAS · MUESTRA REAL" title="Resultados por mapa" />{mapRows.map((row) => <View key={row.mapId} style={o.mapRow}><Text style={o.mapName}>{row.mapId.toUpperCase()}</Text><View style={o.mapSample}><Text style={o.description}>{row.samples.length ? `${row.samples.length} mapas · ${row.winRate.toFixed(0)}% victorias · ${row.rating.toFixed(2)} rating` : 'Sin muestra simulada todavía'}</Text>{row.samples.length ? <ProgressBar value={row.winRate} color={row.winRate >= 50 ? Colors.green : Colors.red} /> : null}</View></View>)}</Panel><Panel><SectionHeader eyebrow="ORGANIZACIÓN" title="Contexto actual" /><Text style={o.description}>{team.tacticalStyle}. Staff {team.staffQuality}/100 · sponsor {team.sponsorLevel}/100 · estabilidad del roster {100 - team.rosterRisk}/100.</Text><Text style={o.description}>Objetivo anual: {team.objective}. Estado: {career.squad.lastChangeReason}</Text></Panel></View>;
}

} */

export function LegacyRosterView() {
  const { career } = useCareerStore(); if (!career) return null; const team = getTeam(career.teamId);
  return <View><SectionHeader eyebrow="ALINEACIÓN ACTIVA" title={`Roster de ${team.name}`} /><Panel>{team.roster.map((player, index) => { const isUser = player.toLowerCase() === career.player.identity.nickname.toLowerCase(); const role = index === 0 ? 'IGL' : index === 2 ? 'AWPer' : index === 4 ? 'Support' : index === 1 ? 'Entry' : 'Rifler'; return <View key={`${player}-${index}`} style={[o.rosterRow, isUser && o.rosterUser]}><View style={o.playerIndex}><Text style={o.playerIndexText}>0{index + 1}</Text></View><View style={o.playerAvatar}><Text style={o.playerAvatarText}>{player.slice(0, 2).toUpperCase()}</Text></View><View style={o.playerCopy}><Text style={o.playerName}>{player}{isUser ? ' · VOS' : ''}</Text><Text style={o.playerRole}>{role} · Titular</Text></View><Badge tone={index === 0 ? 'purple' : index === 2 ? 'orange' : 'neutral'}>{role}</Badge><Text style={o.playerRating}>{isUser ? overallRating(career.player.attributes) : Math.max(60, team.globalLevel + (index * 3) % 9 - 4)}</Text></View>; })}<View style={o.rosterRow}><View style={o.playerIndex}><Text style={o.playerIndexText}>06</Text></View><View style={o.playerAvatar}><Text style={o.playerAvatarText}>{career.player.identity.nickname.slice(0, 2).toUpperCase()}</Text></View><View style={o.playerCopy}><Text style={o.playerName}>{career.player.identity.nickname}</Text><Text style={o.playerRole}>{career.player.identity.role} · {career.player.benched ? 'Banco' : 'Integrado al roster'}</Text></View><Badge tone={career.player.benched ? 'red' : 'green'}>{career.player.benched ? 'BENCHED' : 'ACTIVE'}</Badge><Text style={o.playerRating}>{overallRating(career.player.attributes)}</Text></View></Panel><View style={o.metricGrid}><Panel><Metric label="Relación con el coach" value={career.coachRelationship} /></Panel><Panel><Metric label="IGL relation" value={career.iglRelationship} /></Panel><Panel><Metric label="Team chemistry" value={career.chemistry} tone="green" /></Panel><Panel><Metric label="Roster risk" value={team.rosterRisk} tone={team.rosterRisk > 65 ? 'red' : 'neutral'} /></Panel></View></View>;
}

export function RosterView() {
  const { career } = useCareerStore(); if (!career) return null;
  const team = getTeam(career.teamId);
  const profiles = team.roster.map((nickname) => PRO_PLAYER_POOL.find((profile) => profile.nickname.toLowerCase() === nickname.toLowerCase()));
  return <View><SectionHeader eyebrow="DATOS PERSISTENTES DEL ROSTER" title={`Roster de ${team.name}`} /><Panel><Text style={o.description}>Los perfiles base vienen del seed mundial. Rating, forma y rol simulado solo aparecen cuando el motor tiene una muestra real.</Text>{team.roster.map((nickname, index) => { const profile = profiles[index]; const isUser = nickname.toLowerCase() === career.player.identity.nickname.toLowerCase(); const rankingSample = career.playerRankingHistory.at(-1)?.entries.find((entry) => entry.nickname.toLowerCase() === nickname.toLowerCase()); return <View key={`${nickname}-${index}`} style={[o.rosterRow, isUser && o.rosterUser]}><View style={o.playerIndex}><Text style={o.playerIndexText}>{String(index + 1).padStart(2, '0')}</Text></View><View style={o.playerCopy}><Text style={o.playerName}>{nickname}{isUser ? ' · VOS' : ''}</Text><Text style={o.playerRole}>{profile?.role ?? 'Integrante del roster'} · {profile?.age ?? '—'} años · {isUser ? (career.player.benched ? 'Banco' : 'Titular') : 'Titular base'}</Text></View><Badge tone={rankingSample ? 'green' : 'neutral'}>{rankingSample ? 'SIM' : 'BASE'}</Badge><Text style={o.playerRating}>{isUser ? overallRating(career.player.attributes).toFixed(0) : rankingSample?.rating.toFixed(2) ?? profile?.baseScore.toFixed(0) ?? '—'}</Text></View>; })}</Panel><View style={o.metricGrid}><Panel><Metric label="Química" value={career.chemistry} /></Panel><Panel><Metric label="Estabilidad" value={career.squad.roleSecurity} /></Panel><Panel><Metric label="Relación con el coach" value={career.coachRelationship} /></Panel></View></View>;
}

export function TeamView() {
  const { career } = useCareerStore(); if (!career) return null; const team = getTeam(career.teamId); const rank = career.rankings.find((entry) => entry.teamId === team.id)?.rank ?? team.initialRanking;
  const rows = team.mapPool.map((mapId) => { const samples = career.matches.flatMap((match) => match.maps.filter((map) => map.mapId === mapId)); const wins = samples.filter((map) => map.teamScore > map.opponentScore).length; return { mapId, samples, wins, rating: samples.length ? samples.reduce((sum, map) => sum + map.playerStats.rating, 0) / samples.length : 0 }; });
  return <View><SectionHeader eyebrow="ORGANIZACIÓN ACTUAL" title={team.name} /><Panel accent="orange" style={o.teamHero}><TeamCrest id={team.id} color={team.color} size={88} /><View style={o.teamHeroCopy}><View style={o.badges}><Badge tone="orange">#{rank} VRS</Badge><Badge tone="purple">{team.tier}</Badge><Badge>{team.region}</Badge></View><Text style={o.teamName}>{team.name}</Text><Text style={o.teamMeta}>{team.city}, {team.country} · {team.culture}</Text><Text style={o.objective}>Objetivo: {team.objective}</Text></View></Panel><View style={o.metricGrid}><Panel><Metric label="Ranking VRS actual" value={`#${rank}`} tone="orange" /></Panel><Panel><Metric label="Forma del equipo" value={career.matches.filter((item) => item.won).slice(-5).length} detail="victorias en las últimas 5" /></Panel><Panel><Metric label="Química" value={career.chemistry} /></Panel><Panel><Metric label="Presupuesto" value={`$${(team.budget / 1000000).toFixed(1)}M`} /></Panel></View><Panel><SectionHeader eyebrow="MAPAS · MUESTRA REAL" title="Resultados por mapa" />{rows.map((row) => <View key={row.mapId} style={o.mapRow}><Text style={o.mapName}>{row.mapId.toUpperCase()}</Text><Text style={o.description}>{row.samples.length ? `${row.samples.length} mapas · ${(row.wins / row.samples.length * 100).toFixed(0)}% victorias · ${row.rating.toFixed(2)} rating` : 'Sin muestra simulada todavía'}</Text>{row.samples.length ? <ProgressBar value={row.wins / row.samples.length * 100} color={row.wins >= row.samples.length / 2 ? Colors.green : Colors.red} /> : null}</View>)}</Panel><Panel><SectionHeader eyebrow="ORGANIZACIÓN" title="Contexto actual" /><Text style={o.description}>{team.tacticalStyle}. Staff {team.staffQuality}/100 · sponsor {team.sponsorLevel}/100 · estabilidad del roster {100 - team.rosterRisk}/100.</Text><Text style={o.description}>Objetivo anual: {team.objective}. Estado: {career.squad.lastChangeReason}</Text></Panel></View>;
}

export function LegacyMarketView() {
  const { career, transfer } = useCareerStore(); const [selected, setSelected] = useState<string | null>(null); if (!career) return null; const offers = transferOffers(career); const current = getTeam(career.teamId); const selectedTeam = selected ? getTeam(selected) : null;
  return <View><SectionHeader eyebrow="TRANSFER MARKET" title="Ofertas y oportunidades" /><Panel style={o.marketIntro}><View><Eyebrow>VALOR DE MERCADO</Eyebrow><Text style={o.marketValue}>${career.player.marketValue.toLocaleString('en-US')}</Text><Text style={o.marketMeta}>{current.name} · {career.contract.monthsRemaining} meses de contrato · Buyout ${career.contract.buyout.toLocaleString('en-US')}</Text></View><Badge tone="orange">{offers.length} interesados</Badge></Panel><View style={o.offerGrid}>{offers.map((team) => { const offer = career.offers.find((item) => item.teamId === team.id); return <Pressable key={team.id} onPress={() => setSelected(team.id)} style={[o.offerCard, selected === team.id && o.offerActive]}><View style={o.offerTop}><TeamCrest id={team.id} color={team.color} /><Badge tone={team.tier === 'Tier 1' ? 'orange' : 'neutral'}>#{team.initialRanking}</Badge></View><Text style={o.offerName}>{team.name}</Text><Text style={o.offerMeta}>{team.region} · {offer?.squadRole ?? 'interés exploratorio'} · fit {offer?.fit ?? roleFit(career, team)}%</Text><Divider /><Text style={o.offerSalary}>${(offer?.monthlySalary ?? Math.round(team.averageSalary * 0.8)).toLocaleString('en-US')}<Text style={o.offerSalaryLabel}> / mes</Text></Text><Text style={o.offerObjective}>{offer?.rationale ?? team.objective}</Text></Pressable>; })}</View>{selectedTeam ? <Panel accent="orange" style={o.offerAction}><View><Text style={o.offerActionTitle}>Firmar con {selectedTeam.name}</Text><Text style={o.offerActionCopy}>El contrato define sueldo, duración y lugar inicial en la jerarquía. Un club más grande no garantiza minutos.</Text></View><Button label="Aceptar oferta →" onPress={() => transfer(selectedTeam.id)} /></Panel> : null}</View>;
}

export function MarketView() {
  const { career, transfer } = useCareerStore(); const [selected, setSelected] = useState<string | null>(null); if (!career) return null; const current = getTeam(career.teamId); const selectedTeam = selected ? getTeam(selected) : null;
  const rankOf = (id: string) => career.rankings.find((entry) => entry.teamId === id)?.rank ?? getTeam(id).initialRanking;
  const offers = transferOffers(career).slice().sort((a, b) => rankOf(a.id) - rankOf(b.id)); const roleLabel = (value?: string) => value === 'starter' ? 'Titular' : value === 'rotation' ? 'Rotación' : value === 'prospect' ? 'Promesa' : value === 'benched' ? 'Banco' : 'Interés inicial';
  return <View><SectionHeader eyebrow="MERCADO DE FICHAJES" title="Elegí entre quedarte o cambiar de club" /><Panel style={o.marketIntro}><View><Eyebrow>TU SITUACIÓN ACTUAL</Eyebrow><Text style={o.marketValue}>{current.name}</Text><Text style={o.marketMeta}>Puesto #{rankOf(current.id)} · {roleLabel(career.squad.role)} · ${career.contract.monthlySalary.toLocaleString('en-US')}/mes · {career.contract.monthsRemaining} meses restantes</Text></View><Badge tone="orange">{offers.length} OFERTAS</Badge></Panel>{offers.length ? <View style={o.offerGrid}>{offers.map((offerTeam) => { const offer = career.offers.find((item) => item.teamId === offerTeam.id); const targetRank = rankOf(offerTeam.id); const rankGain = rankOf(current.id) - targetRank; return <Pressable accessibilityRole="button" accessibilityLabel={`Comparar oferta de ${offerTeam.name}`} key={offerTeam.id} onPress={() => setSelected(offerTeam.id)} style={[o.offerCard, selected === offerTeam.id && o.offerActive]}><View style={o.offerTop}><TeamCrest id={offerTeam.id} color={offerTeam.color} /><Badge tone={rankGain > 0 ? 'green' : 'neutral'}>#{targetRank}{rankGain > 0 ? ` · +${rankGain}` : ''}</Badge></View><Text style={o.offerName}>{offerTeam.name}</Text><Text style={o.offerMeta}>{offerTeam.tier} · {roleLabel(offer?.squadRole)} · encaje {offer?.fit ?? roleFit(career, offerTeam)}%</Text><Divider /><Text style={o.offerSalary}>${(offer?.monthlySalary ?? Math.round(offerTeam.averageSalary * .8)).toLocaleString('en-US')} / mes</Text><Text style={o.offerObjective}>{offer?.rationale ?? offerTeam.objective}</Text></Pressable>; })}</View> : <Panel><Text style={o.offerActionTitle}>No llegaron ofertas concretas</Text><Text style={o.offerActionCopy}>Podés quedarte, entrenar y mejorar tu rendimiento para atraer clubes la próxima temporada.</Text></Panel>}{selectedTeam ? <Panel accent="orange" style={o.offerAction}><View style={o.flex}><SectionHeader eyebrow="COMPARACIÓN" title={`${current.name} → ${selectedTeam.name}`} /><Text style={o.offerActionCopy}>Ranking #{rankOf(current.id)} → #{rankOf(selectedTeam.id)} · sueldo ${career.contract.monthlySalary.toLocaleString('en-US')} → ${(career.offers.find((item) => item.teamId === selectedTeam.id)?.monthlySalary ?? selectedTeam.averageSalary).toLocaleString('en-US')} · lugar esperado: {roleLabel(career.offers.find((item) => item.teamId === selectedTeam.id)?.squadRole)}.</Text><Text style={o.offerActionCopy}>Un club mejor posicionado ofrece más exposición, pero el lugar prometido define cuánto vas a jugar.</Text></View><Button label="Aceptar oferta →" onPress={() => transfer(selectedTeam.id)} /></Panel> : null}</View>;
}

export function LegacyContractView() {
  const { career, negotiate } = useCareerStore(); if (!career) return null; const team = getTeam(career.teamId); const contract = career.contract;
  return <View><SectionHeader eyebrow="PLAYER CONTRACT" title={`Contrato con ${team.name}`} /><Panel accent="orange"><View style={o.contractTop}><View><Badge tone="green">ACTIVE</Badge><Text style={o.contractTitle}>{career.player.identity.nickname} × {team.name}</Text><Text style={o.contractSubtitle}>{contract.guaranteedRole} garantizado · {contract.monthsRemaining} meses restantes</Text></View><Text style={o.contractWorth}>${contractValue(contract, career.player.attributes).toLocaleString('en-US')}<Text style={o.contractWorthLabel}> VALUE</Text></Text></View><View style={o.metricGridInner}><Metric label="Salario mensual" value={`$${contract.monthlySalary.toLocaleString('en-US')}`} /><Metric label="Prize share" value={`${contract.prizeShare}%`} /><Metric label="Win bonus" value={`$${contract.winBonus}`} /><Metric label="Major bonus" value={`$${contract.majorBonus}`} /><Metric label="MVP bonus" value={`$${contract.mvpBonus}`} /><Metric label="Buyout" value={`$${contract.buyout.toLocaleString('en-US')}`} /></View></Panel><SectionHeader eyebrow="NEGOTIATION" title="Renegociar prioridades" /><View style={o.negotiations}>{[{ id: 'salary' as const, title: 'Más salario', copy: '+15% sueldo · +20% buyout · +6 meses' }, { id: 'role' as const, title: 'Más influencia', copy: '+15 influencia · -5% sueldo' }, { id: 'freedom' as const, title: 'Más libertad', copy: '+vacaciones · streaming · -2% premios' }].map((item) => <Panel key={item.id} style={o.negotiation}><Text style={o.negotiationTitle}>{item.title}</Text><Text style={o.negotiationCopy}>{item.copy}</Text><Button compact variant="secondary" label="Negociar" onPress={() => negotiate(item.id)} /></Panel>)}</View><Panel><SectionHeader eyebrow="CLAUSES" title="Términos especiales" /><View style={o.clauses}><Badge tone={contract.streamingAllowed ? 'green' : 'red'}>Streaming {contract.streamingAllowed ? 'permitido' : 'restringido'}</Badge><Badge>{contract.vacationWeeks} semanas libres</Badge><Badge tone={contract.personalStaff ? 'green' : 'neutral'}>Staff personal {contract.personalStaff ? 'incluido' : 'no incluido'}</Badge><Badge tone="purple">Influencia {contract.decisionInfluence}</Badge></View></Panel></View>;
}

export function ContractView() {
  const { career, negotiate } = useCareerStore(); if (!career) return null; const team = getTeam(career.teamId); const contract = career.contract; const availability = contractNegotiationAvailability(contract, career.season); const locked = !availability.available;
  return <View><SectionHeader eyebrow="TU CONTRATO" title={`Contrato con ${team.name}`} /><Panel accent="orange"><View style={o.contractTop}><View><Badge tone="green">VIGENTE</Badge><Text style={o.contractTitle}>{career.player.identity.nickname} × {team.name}</Text><Text style={o.contractSubtitle}>{contract.guaranteedRole} · {contract.monthsRemaining} meses restantes</Text></View><Text style={o.contractWorth}>${contractValue(contract, career.player.attributes).toLocaleString('en-US')}</Text></View><View style={o.metricGridInner}><Metric label="Salario mensual" value={`$${contract.monthlySalary.toLocaleString('en-US')}`} /><Metric label="Porcentaje de premios" value={`${contract.prizeShare}%`} /><Metric label="Cláusula de salida" value={`$${contract.buyout.toLocaleString('en-US')}`} /><Metric label="Próxima negociación" value={locked ? `Temporada ${availability.availableSeason}` : 'DISPONIBLE'} tone={locked ? 'red' : 'green'} /></View></Panel><SectionHeader eyebrow="NEGOCIACIÓN" title="Elegí qué querés mejorar" /><View style={o.negotiations}>{[{ id: 'salary' as const, title: 'Más salario', copy: '+15% de sueldo · nueva negociación en 2 temporadas' }, { id: 'role' as const, title: 'Más influencia', copy: '+15 de influencia · nueva negociación en 2 temporadas' }, { id: 'freedom' as const, title: 'Más libertad', copy: '+vacaciones · nueva negociación en 2 temporadas' }].map((item) => <Panel key={item.id} style={o.negotiation}><Text style={o.negotiationTitle}>{item.title}</Text><Text style={o.negotiationCopy}>{item.copy}</Text><Button compact disabled={locked} variant="secondary" label={locked ? `Disponible en temporada ${availability.availableSeason}` : 'Negociar'} onPress={() => negotiate(item.id)} /></Panel>)}</View><Panel><Text style={o.description}>Última negociación: {contract.lastNegotiationSeason ? `temporada ${contract.lastNegotiationSeason}` : 'ninguna'}. El resultado depende de rendimiento, reputación, valor de mercado y relación con el equipo.</Text></Panel></View>;
}

export function TrainingView() {
  const { career, train } = useCareerStore(); if (!career) return null;
  return <View><SectionHeader eyebrow="DESARROLLO DEL JUGADOR" title="Asignar puntos de entrenamiento" /><Panel accent="orange" style={o.trainingNotice}><Text style={o.trainingNoticeTitle}>Tenés {career.player.trainingPoints} TP disponibles</Text><Text style={o.trainingNoticeCopy}>Elegí una actividad. El costo se descuenta en el momento y la vista muestra exactamente qué atributos van a mejorar.</Text></Panel><View style={o.trainingSummary}><Panel><Metric label="Puntos disponibles" value={career.player.trainingPoints} tone="orange" detail="Se ganan compitiendo y subiendo de nivel" /></Panel><Panel><Metric label="Dinero disponible" value={`$${career.player.money.toLocaleString('en-US')}`} /></Panel><Panel><Metric label="Fatiga" value={career.player.fatigue} tone={career.player.fatigue > 70 ? 'red' : 'neutral'} /></Panel><Panel><Metric label="Burnout" value={career.player.burnout} tone={career.player.burnout > 65 ? 'red' : 'neutral'} /></Panel></View><View style={o.trainingGrid}>{TRAINING_ACTIVITIES.map((activity) => { const availability = trainingAvailability(career, activity); return <Panel key={activity.id} style={o.trainingCard}><View style={o.trainingTop}><Badge tone={activity.fatigue < 0 ? 'green' : activity.fatigue > 10 ? 'red' : 'orange'}>{activity.fatigue >= 0 ? `+${activity.fatigue}` : activity.fatigue} FAT</Badge><Text style={o.trainingCost}>{activity.pointCost} TP{activity.moneyCost ? ` · $${activity.moneyCost.toLocaleString('en-US')}` : ''}</Text></View><Text style={o.trainingName}>{activity.name}</Text><Text style={o.trainingDescription}>{activity.description}</Text><View style={o.trainingAttributes}>{activity.attributes.map((attribute) => <Text key={attribute} style={o.trainingAttribute}>{ATTRIBUTE_LABELS[attribute]} · {career.player.attributes[attribute]} → {Math.min(100, career.player.attributes[attribute] + availability.projectedGain)}</Text>)}</View><Button compact disabled={!availability.available} label={availability.reason} onPress={() => train(activity)} /></Panel>; })}</View></View>;
}

export function HealthView() {
  const { career, train } = useCareerStore(); if (!career) return null; const rest = TRAINING_ACTIVITIES.find((activity) => activity.id === 'rest')!;
  const condition = career.player.injuredWeeks > 0 ? 'Lesionado' : career.player.fatigue > 78 ? 'Sobrecarga' : career.player.burnout > 70 ? 'Burnout alto' : 'Apto para competir';
  return <View><SectionHeader eyebrow="PERFORMANCE & WELLNESS" title="Salud y fatiga" /><Panel accent={career.player.injuredWeeks ? 'red' : 'green'} style={o.healthHero}><View><Badge tone={career.player.injuredWeeks ? 'red' : 'green'}>{condition}</Badge><Text style={o.healthTitle}>{career.player.injuredWeeks ? `${career.player.injuredWeeks} semana(s) de recuperación` : 'Estado competitivo estable'}</Text><Text style={o.healthCopy}>La fatiga y el burnout reducen directamente tu performance score, aumentan lesiones y acortan la carrera.</Text></View><Button label="Programar descanso" disabled={career.player.trainingPoints < rest.pointCost} onPress={() => train(rest)} /></Panel><View style={o.healthGrid}><HealthGauge label="Fatiga" value={career.player.fatigue} danger={70} /><HealthGauge label="Burnout" value={career.player.burnout} danger={65} /><HealthGauge label="Riesgo de lesión" value={career.player.injuryRisk} danger={55} /><HealthGauge label="Presión" value={career.player.pressure} danger={70} /><HealthGauge label="Motivación" value={career.player.motivation} danger={101} positive /><HealthGauge label="Stamina" value={career.player.attributes.stamina} danger={101} positive /></View><Panel><SectionHeader eyebrow="MEDICAL REPORT" title="Factores actuales" /><Text style={o.description}>Carga competitiva: {career.matches.filter((match) => match.season === career.season).length} series esta temporada.</Text><Text style={o.description}>Desgaste acumulado: {Math.round(career.player.fatigue * 0.55 + career.player.burnout * 0.45)}/100.</Text><Text style={o.description}>Longevidad proyectada: {Math.max(career.player.identity.age + 1, Math.round(37 - career.player.burnout / 18 + career.player.attributes.discipline / 30))} años.</Text></Panel></View>;
}

function HealthGauge({ label, value, danger, positive = false }: { label: string; value: number; danger: number; positive?: boolean }) { const bad = positive ? value < 45 : value >= danger; const color = bad ? Colors.red : positive ? Colors.green : Colors.orange; return <Panel style={o.healthGauge}><View style={o.healthGaugeTop}><Text style={o.healthLabel}>{label}</Text><Text style={[o.healthValue, { color }]}>{Math.round(value)}</Text></View><ProgressBar value={value} color={color} /><Text style={o.healthStatus}>{bad ? 'Requiere atención' : 'Dentro del rango'}</Text></Panel>; }

export function TrophiesView() {
  const { career } = useCareerStore(); if (!career) return null;
  return <View><SectionHeader eyebrow="TROPHY CABINET" title="Historial de títulos" /><View style={o.trophyHero}><Panel><Metric label="Títulos" value={career.trophies.length} tone="orange" /></Panel><Panel><Metric label="Majors" value={career.trophies.filter((item) => item.name.includes('Major')).length} tone="green" /></Panel><Panel><Metric label="MVPs" value={career.trophies.filter((item) => item.mvp).length} /></Panel></View><View style={o.trophyGrid}>{career.trophies.length ? career.trophies.map((trophy) => <Panel key={trophy.id} accent="orange" style={o.trophyCard}><Text style={o.trophyIcon}>✦</Text><Badge tone="orange">{trophy.tier}-TIER</Badge><Text style={o.trophyName}>{trophy.name}</Text><Text style={o.trophyMeta}>Temporada {trophy.season}{trophy.mvp ? ' · MVP' : ''}</Text></Panel>) : <Panel style={o.emptyPanel}><Text style={o.emptyTitle}>La vitrina todavía está vacía.</Text><Text style={o.description}>Clasificá, ganá series y levantá tu primer trofeo.</Text></Panel>}</View></View>;
}

export function RivalriesView() {
  const { career } = useCareerStore(); if (!career) return null; const team = getTeam(career.teamId); const rivalIds = new Set([...team.rivals, ...Object.keys(career.rivalries), ...career.matches.slice(-12).map((match) => match.opponentTeamId)]); const rivals = [...rivalIds].slice(0, 10).map((id) => ({ team: getTeam(id), heat: career.rivalries[id] ?? 25 + career.matches.filter((match) => match.opponentTeamId === id).length * 12 }));
  return <View><SectionHeader eyebrow="RIVALRY TRACKER" title="Enemigos deportivos" /><View style={o.rivalGrid}>{rivals.length ? rivals.map(({ team: rival, heat }) => <Panel key={rival.id} style={o.rivalCard}><View style={o.rivalTop}><TeamCrest id={rival.id} color={rival.color} /><View style={o.rivalCopy}><Text style={o.rivalName}>{rival.name}</Text><Text style={o.rivalMeta}>{career.matches.filter((match) => match.opponentTeamId === rival.id).length} series jugadas</Text></View><Text style={o.rivalHeat}>{Math.min(100, heat)}</Text></View><ProgressBar value={Math.min(100, heat)} color={heat > 65 ? Colors.red : Colors.orange} /><Text style={o.rivalStatus}>{heat > 75 ? 'Rivalidad histórica' : heat > 45 ? 'Tensión creciente' : 'Competencia deportiva'}</Text></Panel>) : <Panel><Text style={o.description}>Todavía no construiste una rivalidad. Los cruces repetidos y las decisiones públicas aumentan la tensión.</Text></Panel>}</View></View>;
}

const o = StyleSheet.create({
  teamHero: { flexDirection: 'row', alignItems: 'center', gap: 20, flexWrap: 'wrap', marginBottom: 12 }, teamHeroCopy: { flex: 1, minWidth: 250 }, badges: { flexDirection: 'row', flexWrap: 'wrap', gap: 5 }, teamName: { color: Colors.text, fontSize: 36, fontWeight: '900', marginTop: 12 }, teamMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 11, marginTop: 5 }, objective: { color: Colors.textSoft, fontSize: 13, marginTop: 13 }, metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 }, twoColumns: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, flex: { flex: 1, minWidth: 280 }, description: { color: Colors.textSoft, fontSize: 12, lineHeight: 19, marginBottom: 6 }, mapRow: { marginBottom: 13 }, mapRank: { color: Colors.orange, fontFamily: Fonts.mono, fontSize: 10 }, mapName: { color: Colors.text, fontSize: 11, fontWeight: '900', marginVertical: 5 },
  rosterRow: { minHeight: 66, flexDirection: 'row', alignItems: 'center', gap: 11, paddingHorizontal: 8, borderBottomWidth: 1, borderBottomColor: Colors.line }, rosterUser: { backgroundColor: Colors.orangeSoft, borderLeftWidth: 2, borderLeftColor: Colors.orange }, playerIndex: { width: 24 }, playerIndexText: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 11 }, playerAvatar: { width: 36, height: 36, backgroundColor: Colors.panelSoft, borderWidth: 1, borderColor: Colors.lineStrong, alignItems: 'center', justifyContent: 'center' }, playerAvatarText: { color: Colors.textSoft, fontFamily: Fonts.mono, fontSize: 11, fontWeight: '900' }, playerCopy: { flex: 1 }, playerName: { color: Colors.text, fontSize: 14, fontWeight: '900' }, playerRole: { color: Colors.textSoft, fontFamily: Fonts.sans, fontSize: 11, marginTop: 4 }, playerRating: { width: 36, color: Colors.orange, fontSize: 17, fontWeight: '900', textAlign: 'right' },
  marketIntro: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: 15, marginBottom: 16 }, marketValue: { color: Colors.orange, fontSize: 40, fontWeight: '900' }, marketMeta: { color: Colors.textSoft, fontFamily: Fonts.sans, fontSize: 12, marginTop: 6 }, offerGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, offerCard: { minWidth: 210, flexGrow: 1, flexBasis: 230, padding: 15, backgroundColor: Colors.panel, borderWidth: 1, borderColor: Colors.line }, offerActive: { borderColor: Colors.orange, backgroundColor: Colors.orangeSoft }, offerTop: { flexDirection: 'row', justifyContent: 'space-between' }, offerName: { color: Colors.text, fontSize: 15, fontWeight: '900', marginTop: 12 }, offerMeta: { color: Colors.textSoft, fontFamily: Fonts.sans, fontSize: 11, marginTop: 4 }, offerSalary: { color: Colors.green, fontSize: 18, fontWeight: '900' }, offerSalaryLabel: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 10 }, offerObjective: { color: Colors.textSoft, fontSize: 12, lineHeight: 17, marginTop: 8 }, offerAction: { flexDirection: 'row', alignItems: 'center', gap: 18, marginTop: 14 }, offerActionTitle: { color: Colors.text, fontSize: 15, fontWeight: '900' }, offerActionCopy: { color: Colors.textSoft, fontSize: 12, lineHeight: 18, marginTop: 5, flex: 1 },
  contractTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', flexWrap: 'wrap', gap: 16 }, contractTitle: { color: Colors.text, fontSize: 25, fontWeight: '900', marginTop: 12 }, contractSubtitle: { color: Colors.textSoft, fontSize: 12, marginTop: 5 }, contractWorth: { color: Colors.orange, fontSize: 31, fontWeight: '900' }, contractWorthLabel: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 10 }, metricGridInner: { flexDirection: 'row', flexWrap: 'wrap', gap: 17, marginTop: 25 }, negotiations: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginBottom: 20 }, negotiation: { minWidth: 230, flex: 1 }, negotiationTitle: { color: Colors.text, fontSize: 14, fontWeight: '900' }, negotiationCopy: { color: Colors.muted, fontSize: 11, marginVertical: 9 }, clauses: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  trainingNotice: { marginBottom: 14 }, trainingNoticeTitle: { color: Colors.text, fontFamily: Fonts.sans, fontSize: 18, lineHeight: 23, fontWeight: '900' }, trainingNoticeCopy: { color: Colors.textSoft, fontFamily: Fonts.sans, fontSize: 13, lineHeight: 20, marginTop: 5 }, trainingSummary: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 }, trainingGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, trainingCard: { minWidth: 235, flexGrow: 1, flexBasis: 270 }, trainingTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 10 }, trainingCost: { color: Colors.textSoft, fontFamily: Fonts.mono, fontSize: 10, lineHeight: 15 }, trainingName: { color: Colors.text, fontSize: 17, lineHeight: 22, fontWeight: '900', marginTop: 13 }, trainingDescription: { color: Colors.textSoft, fontSize: 13, lineHeight: 19, marginTop: 6 }, trainingAttributes: { marginVertical: 13 }, trainingAttribute: { color: Colors.green, fontFamily: Fonts.sans, fontSize: 11, lineHeight: 16, fontWeight: '700', marginBottom: 5 },
  healthHero: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 18, marginBottom: 16 }, healthTitle: { color: Colors.text, fontSize: 21, fontWeight: '900', marginTop: 13 }, healthCopy: { color: Colors.textSoft, fontSize: 12, lineHeight: 19, marginTop: 6, maxWidth: 650 }, healthGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginBottom: 20 }, healthGauge: { minWidth: 190, flexGrow: 1, flexBasis: 220 }, healthGaugeTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 9 }, healthLabel: { color: Colors.text, fontSize: 11, fontWeight: '900' }, healthValue: { fontSize: 24, fontWeight: '900' }, healthStatus: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 10, marginTop: 7 },
  trophyHero: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 }, trophyGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, trophyCard: { minWidth: 230, flex: 1, alignItems: 'center', paddingVertical: 28 }, trophyIcon: { color: Colors.orange, fontSize: 42, marginBottom: 12 }, trophyName: { color: Colors.text, fontSize: 15, fontWeight: '900', textAlign: 'center', marginTop: 12 }, trophyMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 10, marginTop: 6 }, emptyPanel: { flex: 1 }, emptyTitle: { color: Colors.text, fontSize: 16, fontWeight: '900', marginBottom: 7 },
  rivalGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, rivalCard: { minWidth: 250, flexGrow: 1, flexBasis: 300 }, rivalTop: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 }, rivalCopy: { flex: 1, marginLeft: 11 }, rivalName: { color: Colors.text, fontSize: 13, fontWeight: '900' }, rivalMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 10, marginTop: 4 }, rivalHeat: { color: Colors.red, fontSize: 23, fontWeight: '900' }, rivalStatus: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 10, marginTop: 8 },
});
