import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { Badge, Button, Divider, Eyebrow, Metric, Panel, ProgressBar, SectionHeader, StatRow, TeamMark } from '@/components/ui/game-ui';
import { Colors, Fonts } from '@/constants/theme';
import { ATTRIBUTE_LABELS } from '@/data/roles';
import { getTeam } from '@/data/teams';
import { TRAINING_ACTIVITIES } from '@/data/training';
import { contractValue } from '@/engine/contracts';
import { transferOffers } from '@/engine/rosters';
import { overallRating } from '@/engine/progression';
import { useCareerStore } from '@/state/career-store';

export function TeamView() {
  const { career } = useCareerStore(); if (!career) return null; const team = getTeam(career.teamId);
  return <View><SectionHeader eyebrow="CURRENT ORGANIZATION" title={team.name} /><Panel accent="orange" style={o.teamHero}><TeamMark code={team.abbreviation} color={team.color} size={88} /><View style={o.teamHeroCopy}><View style={o.badges}><Badge tone="orange">#{career.rankings.find((entry) => entry.teamId === team.id)?.rank} VRS</Badge><Badge tone="purple">{team.tier}</Badge><Badge>{team.region}</Badge></View><Text style={o.teamName}>{team.name}</Text><Text style={o.teamMeta}>{team.city}, {team.country} · {team.culture}</Text><Text style={o.objective}>Objetivo: {team.objective}</Text></View></Panel><View style={o.metricGrid}><Panel><Metric label="Nivel global" value={team.globalLevel} tone="orange" /></Panel><Panel><Metric label="Química" value={career.chemistry} tone={career.chemistry >= 70 ? 'green' : 'neutral'} /></Panel><Panel><Metric label="Coach" value={team.coachQuality} /></Panel><Panel><Metric label="Analista" value={team.analystQuality} /></Panel><Panel><Metric label="Estabilidad" value={team.stability} /></Panel><Panel><Metric label="Budget" value={`$${(team.budget / 1000000).toFixed(1)}M`} /></Panel></View><View style={o.twoColumns}><Panel style={o.flex}><SectionHeader eyebrow="IDENTIDAD" title="Estilo competitivo" /><StatRow label="Agresividad" value={team.aggression} color={Colors.red} /><StatRow label="Staff" value={team.staffQuality} color={Colors.blue} /><StatRow label="Sponsor" value={team.sponsorLevel} color={Colors.green} /><StatRow label="Actividad de mercado" value={team.transferActivity} color={Colors.orange} /><Divider /><Text style={o.description}>{team.tacticalStyle}. La organización prioriza una cultura {team.culture.toLowerCase()}.</Text></Panel><Panel style={o.flex}><SectionHeader eyebrow="MAP POOL" title="Mapas preferidos" />{team.mapPool.map((map, index) => <View key={map} style={o.mapRow}><Text style={o.mapRank}>0{index + 1}</Text><Text style={o.mapName}>{map.toUpperCase()}</Text><ProgressBar value={Math.max(52, 88 - index * 7)} color={index < 2 ? Colors.orange : Colors.blue} /></View>)}</Panel></View></View>;
}

export function RosterView() {
  const { career } = useCareerStore(); if (!career) return null; const team = getTeam(career.teamId);
  return <View><SectionHeader eyebrow="ACTIVE LINEUP" title={`Roster de ${team.name}`} /><Panel>{team.roster.map((player, index) => { const isUser = player.toLowerCase() === career.player.identity.nickname.toLowerCase(); const role = index === 0 ? 'IGL' : index === 2 ? 'AWPer' : index === 4 ? 'Support' : index === 1 ? 'Entry' : 'Rifler'; return <View key={`${player}-${index}`} style={[o.rosterRow, isUser && o.rosterUser]}><View style={o.playerIndex}><Text style={o.playerIndexText}>0{index + 1}</Text></View><View style={o.playerAvatar}><Text style={o.playerAvatarText}>{player.slice(0, 2).toUpperCase()}</Text></View><View style={o.playerCopy}><Text style={o.playerName}>{player}{isUser ? ' · VOS' : ''}</Text><Text style={o.playerRole}>{role} · Titular</Text></View><Badge tone={index === 0 ? 'purple' : index === 2 ? 'orange' : 'neutral'}>{role}</Badge><Text style={o.playerRating}>{isUser ? overallRating(career.player.attributes) : Math.max(60, team.globalLevel + (index * 3) % 9 - 4)}</Text></View>; })}<View style={o.rosterRow}><View style={o.playerIndex}><Text style={o.playerIndexText}>06</Text></View><View style={o.playerAvatar}><Text style={o.playerAvatarText}>{career.player.identity.nickname.slice(0, 2).toUpperCase()}</Text></View><View style={o.playerCopy}><Text style={o.playerName}>{career.player.identity.nickname}</Text><Text style={o.playerRole}>{career.player.identity.role} · {career.player.benched ? 'Banco' : 'Integrado al roster'}</Text></View><Badge tone={career.player.benched ? 'red' : 'green'}>{career.player.benched ? 'BENCHED' : 'ACTIVE'}</Badge><Text style={o.playerRating}>{overallRating(career.player.attributes)}</Text></View></Panel><View style={o.metricGrid}><Panel><Metric label="Coach relation" value={career.coachRelationship} /></Panel><Panel><Metric label="IGL relation" value={career.iglRelationship} /></Panel><Panel><Metric label="Team chemistry" value={career.chemistry} tone="green" /></Panel><Panel><Metric label="Roster risk" value={team.rosterRisk} tone={team.rosterRisk > 65 ? 'red' : 'neutral'} /></Panel></View></View>;
}

export function MarketView() {
  const { career, transfer } = useCareerStore(); const [selected, setSelected] = useState<string | null>(null); if (!career) return null; const offers = transferOffers(career); const current = getTeam(career.teamId); const selectedTeam = selected ? getTeam(selected) : null;
  return <View><SectionHeader eyebrow="TRANSFER MARKET" title="Ofertas y oportunidades" /><Panel style={o.marketIntro}><View><Eyebrow>VALOR DE MERCADO</Eyebrow><Text style={o.marketValue}>${career.player.marketValue.toLocaleString('en-US')}</Text><Text style={o.marketMeta}>{current.name} · {career.contract.monthsRemaining} meses de contrato · Buyout ${career.contract.buyout.toLocaleString('en-US')}</Text></View><Badge tone="orange">{offers.length} interesados</Badge></Panel><View style={o.offerGrid}>{offers.map((team) => <Pressable key={team.id} onPress={() => setSelected(team.id)} style={[o.offerCard, selected === team.id && o.offerActive]}><View style={o.offerTop}><TeamMark code={team.abbreviation} color={team.color} /><Badge tone={team.tier === 'Tier 1' ? 'orange' : 'neutral'}>#{team.initialRanking}</Badge></View><Text style={o.offerName}>{team.name}</Text><Text style={o.offerMeta}>{team.region} · {team.tier}</Text><Divider /><Text style={o.offerSalary}>${Math.round(team.averageSalary * 0.8).toLocaleString('en-US')}<Text style={o.offerSalaryLabel}> / mes</Text></Text><Text style={o.offerObjective}>{team.objective}</Text></Pressable>)}</View>{selectedTeam ? <Panel accent="orange" style={o.offerAction}><View><Text style={o.offerActionTitle}>Firmar con {selectedTeam.name}</Text><Text style={o.offerActionCopy}>La transferencia reinicia parte de la química, mejora el contrato y agrega un nuevo capítulo a tu timeline.</Text></View><Button label="Aceptar oferta →" onPress={() => transfer(selectedTeam.id)} /></Panel> : null}</View>;
}

export function ContractView() {
  const { career, negotiate } = useCareerStore(); if (!career) return null; const team = getTeam(career.teamId); const contract = career.contract;
  return <View><SectionHeader eyebrow="PLAYER CONTRACT" title={`Contrato con ${team.name}`} /><Panel accent="orange"><View style={o.contractTop}><View><Badge tone="green">ACTIVE</Badge><Text style={o.contractTitle}>{career.player.identity.nickname} × {team.name}</Text><Text style={o.contractSubtitle}>{contract.guaranteedRole} garantizado · {contract.monthsRemaining} meses restantes</Text></View><Text style={o.contractWorth}>${contractValue(contract, career.player.attributes).toLocaleString('en-US')}<Text style={o.contractWorthLabel}> VALUE</Text></Text></View><View style={o.metricGridInner}><Metric label="Salario mensual" value={`$${contract.monthlySalary.toLocaleString('en-US')}`} /><Metric label="Prize share" value={`${contract.prizeShare}%`} /><Metric label="Win bonus" value={`$${contract.winBonus}`} /><Metric label="Major bonus" value={`$${contract.majorBonus}`} /><Metric label="MVP bonus" value={`$${contract.mvpBonus}`} /><Metric label="Buyout" value={`$${contract.buyout.toLocaleString('en-US')}`} /></View></Panel><SectionHeader eyebrow="NEGOTIATION" title="Renegociar prioridades" /><View style={o.negotiations}>{[{ id: 'salary' as const, title: 'Más salario', copy: '+15% sueldo · +20% buyout · +6 meses' }, { id: 'role' as const, title: 'Más influencia', copy: '+15 influencia · -5% sueldo' }, { id: 'freedom' as const, title: 'Más libertad', copy: '+vacaciones · streaming · -2% premios' }].map((item) => <Panel key={item.id} style={o.negotiation}><Text style={o.negotiationTitle}>{item.title}</Text><Text style={o.negotiationCopy}>{item.copy}</Text><Button compact variant="secondary" label="Negociar" onPress={() => negotiate(item.id)} /></Panel>)}</View><Panel><SectionHeader eyebrow="CLAUSES" title="Términos especiales" /><View style={o.clauses}><Badge tone={contract.streamingAllowed ? 'green' : 'red'}>Streaming {contract.streamingAllowed ? 'permitido' : 'restringido'}</Badge><Badge>{contract.vacationWeeks} semanas libres</Badge><Badge tone={contract.personalStaff ? 'green' : 'neutral'}>Staff personal {contract.personalStaff ? 'incluido' : 'no incluido'}</Badge><Badge tone="purple">Influencia {contract.decisionInfluence}</Badge></View></Panel></View>;
}

export function TrainingView() {
  const { career, train } = useCareerStore(); if (!career) return null;
  return <View><SectionHeader eyebrow="PLAYER DEVELOPMENT" title="Centro de entrenamiento" /><View style={o.trainingSummary}><Panel><Metric label="Training points" value={career.player.trainingPoints} tone="orange" detail="Se ganan con semanas, partidos y objetivos" /></Panel><Panel><Metric label="Fatiga" value={career.player.fatigue} tone={career.player.fatigue > 70 ? 'red' : 'neutral'} /></Panel><Panel><Metric label="Burnout" value={career.player.burnout} tone={career.player.burnout > 65 ? 'red' : 'neutral'} /></Panel><Panel><Metric label="XP" value={career.player.xp} tone="green" /></Panel></View><View style={o.trainingGrid}>{TRAINING_ACTIVITIES.map((activity) => { const disabled = career.player.trainingPoints < activity.pointCost || career.player.money < activity.moneyCost; return <Panel key={activity.id} style={o.trainingCard}><View style={o.trainingTop}><Badge tone={activity.fatigue < 0 ? 'green' : activity.fatigue > 10 ? 'red' : 'orange'}>{activity.fatigue >= 0 ? `+${activity.fatigue}` : activity.fatigue} FAT</Badge><Text style={o.trainingCost}>{activity.pointCost} TP {activity.moneyCost ? `· $${activity.moneyCost}` : ''}</Text></View><Text style={o.trainingName}>{activity.name}</Text><Text style={o.trainingDescription}>{activity.description}</Text><View style={o.trainingAttributes}>{activity.attributes.map((attribute) => <Text key={attribute} style={o.trainingAttribute}>+ {ATTRIBUTE_LABELS[attribute]}</Text>)}</View><Button compact disabled={disabled} label={disabled ? 'Sin recursos' : 'Entrenar'} onPress={() => train(activity)} /></Panel>; })}</View></View>;
}

export function HealthView() {
  const { career, train } = useCareerStore(); if (!career) return null; const rest = TRAINING_ACTIVITIES.find((activity) => activity.id === 'rest')!;
  const condition = career.player.injuredWeeks > 0 ? 'Lesionado' : career.player.fatigue > 78 ? 'Sobrecarga' : career.player.burnout > 70 ? 'Burnout alto' : 'Apto para competir';
  return <View><SectionHeader eyebrow="PERFORMANCE & WELLNESS" title="Salud y fatiga" /><Panel accent={career.player.injuredWeeks ? 'red' : 'green'} style={o.healthHero}><View><Badge tone={career.player.injuredWeeks ? 'red' : 'green'}>{condition}</Badge><Text style={o.healthTitle}>{career.player.injuredWeeks ? `${career.player.injuredWeeks} semana(s) de recuperación` : 'Estado competitivo estable'}</Text><Text style={o.healthCopy}>La fatiga y el burnout reducen directamente tu performance score, aumentan lesiones y acortan la carrera.</Text></View><Button label="Programar descanso" disabled={career.player.trainingPoints < rest.pointCost} onPress={() => train(rest)} /></Panel><View style={o.healthGrid}><HealthGauge label="Fatiga" value={career.player.fatigue} danger={70} /><HealthGauge label="Burnout" value={career.player.burnout} danger={65} /><HealthGauge label="Riesgo de lesión" value={career.player.injuryRisk} danger={55} /><HealthGauge label="Presión" value={career.player.pressure} danger={70} /><HealthGauge label="Motivación" value={career.player.motivation} danger={101} positive /><HealthGauge label="Stamina" value={career.player.attributes.stamina} danger={101} positive /></View><Panel><SectionHeader eyebrow="MEDICAL REPORT" title="Factores actuales" /><Text style={o.description}>Carga competitiva: {career.matches.filter((match) => match.season === career.season).length} series esta temporada.</Text><Text style={o.description}>Desgaste acumulado: {Math.round(career.player.fatigue * 0.55 + career.player.burnout * 0.45)}/100.</Text><Text style={o.description}>Longevidad proyectada: {Math.max(career.player.identity.age + 1, Math.round(37 - career.player.burnout / 18 + career.player.attributes.discipline / 30))} años.</Text></Panel></View>;
}

function HealthGauge({ label, value, danger, positive = false }: { label: string; value: number; danger: number; positive?: boolean }) { const bad = positive ? value < 45 : value >= danger; const color = bad ? Colors.red : positive ? Colors.green : Colors.orange; return <Panel style={o.healthGauge}><View style={o.healthGaugeTop}><Text style={o.healthLabel}>{label}</Text><Text style={[o.healthValue, { color }]}>{Math.round(value)}</Text></View><ProgressBar value={value} color={color} /><Text style={o.healthStatus}>{bad ? 'Requiere atención' : 'Dentro del rango'}</Text></Panel>; }

export function TrophiesView() {
  const { career } = useCareerStore(); if (!career) return null;
  return <View><SectionHeader eyebrow="TROPHY CABINET" title="Historial de títulos" /><View style={o.trophyHero}><Panel><Metric label="Títulos" value={career.trophies.length} tone="orange" /></Panel><Panel><Metric label="Majors" value={career.trophies.filter((item) => item.name.includes('Major')).length} tone="green" /></Panel><Panel><Metric label="MVPs" value={career.trophies.filter((item) => item.mvp).length} /></Panel></View><View style={o.trophyGrid}>{career.trophies.length ? career.trophies.map((trophy) => <Panel key={trophy.id} accent="orange" style={o.trophyCard}><Text style={o.trophyIcon}>✦</Text><Badge tone="orange">{trophy.tier}-TIER</Badge><Text style={o.trophyName}>{trophy.name}</Text><Text style={o.trophyMeta}>Temporada {trophy.season}{trophy.mvp ? ' · MVP' : ''}</Text></Panel>) : <Panel style={o.emptyPanel}><Text style={o.emptyTitle}>La vitrina todavía está vacía.</Text><Text style={o.description}>Clasificá, ganá series y levantá tu primer trofeo.</Text></Panel>}</View></View>;
}

export function RivalriesView() {
  const { career } = useCareerStore(); if (!career) return null; const team = getTeam(career.teamId); const rivalIds = new Set([...team.rivals, ...Object.keys(career.rivalries), ...career.matches.slice(-12).map((match) => match.opponentTeamId)]); const rivals = [...rivalIds].slice(0, 10).map((id) => ({ team: getTeam(id), heat: career.rivalries[id] ?? 25 + career.matches.filter((match) => match.opponentTeamId === id).length * 12 }));
  return <View><SectionHeader eyebrow="RIVALRY TRACKER" title="Enemigos deportivos" /><View style={o.rivalGrid}>{rivals.length ? rivals.map(({ team: rival, heat }) => <Panel key={rival.id} style={o.rivalCard}><View style={o.rivalTop}><TeamMark code={rival.abbreviation} color={rival.color} /><View style={o.rivalCopy}><Text style={o.rivalName}>{rival.name}</Text><Text style={o.rivalMeta}>{career.matches.filter((match) => match.opponentTeamId === rival.id).length} series jugadas</Text></View><Text style={o.rivalHeat}>{Math.min(100, heat)}</Text></View><ProgressBar value={Math.min(100, heat)} color={heat > 65 ? Colors.red : Colors.orange} /><Text style={o.rivalStatus}>{heat > 75 ? 'Rivalidad histórica' : heat > 45 ? 'Tensión creciente' : 'Competencia deportiva'}</Text></Panel>) : <Panel><Text style={o.description}>Todavía no construiste una rivalidad. Los cruces repetidos y las decisiones públicas aumentan la tensión.</Text></Panel>}</View></View>;
}

const o = StyleSheet.create({
  teamHero: { flexDirection: 'row', alignItems: 'center', gap: 20, flexWrap: 'wrap', marginBottom: 12 }, teamHeroCopy: { flex: 1, minWidth: 250 }, badges: { flexDirection: 'row', flexWrap: 'wrap', gap: 5 }, teamName: { color: Colors.text, fontSize: 36, fontWeight: '900', marginTop: 12 }, teamMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 9, marginTop: 5 }, objective: { color: Colors.textSoft, fontSize: 11, marginTop: 13 }, metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 }, twoColumns: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, flex: { flex: 1, minWidth: 280 }, description: { color: Colors.muted, fontSize: 11, lineHeight: 18, marginBottom: 6 }, mapRow: { marginBottom: 13 }, mapRank: { color: Colors.orange, fontFamily: Fonts.mono, fontSize: 8 }, mapName: { color: Colors.text, fontSize: 11, fontWeight: '900', marginVertical: 5 },
  rosterRow: { minHeight: 66, flexDirection: 'row', alignItems: 'center', gap: 11, paddingHorizontal: 8, borderBottomWidth: 1, borderBottomColor: Colors.line }, rosterUser: { backgroundColor: Colors.orangeSoft, borderLeftWidth: 2, borderLeftColor: Colors.orange }, playerIndex: { width: 24 }, playerIndexText: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 9 }, playerAvatar: { width: 36, height: 36, backgroundColor: Colors.panelSoft, borderWidth: 1, borderColor: Colors.lineStrong, alignItems: 'center', justifyContent: 'center' }, playerAvatarText: { color: Colors.textSoft, fontFamily: Fonts.mono, fontSize: 9, fontWeight: '900' }, playerCopy: { flex: 1 }, playerName: { color: Colors.text, fontSize: 12, fontWeight: '900' }, playerRole: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, marginTop: 4 }, playerRating: { width: 36, color: Colors.orange, fontSize: 17, fontWeight: '900', textAlign: 'right' },
  marketIntro: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: 15, marginBottom: 16 }, marketValue: { color: Colors.orange, fontSize: 40, fontWeight: '900' }, marketMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, marginTop: 6 }, offerGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, offerCard: { minWidth: 210, flexGrow: 1, flexBasis: 230, padding: 15, backgroundColor: Colors.panel, borderWidth: 1, borderColor: Colors.line }, offerActive: { borderColor: Colors.orange, backgroundColor: Colors.orangeSoft }, offerTop: { flexDirection: 'row', justifyContent: 'space-between' }, offerName: { color: Colors.text, fontSize: 15, fontWeight: '900', marginTop: 12 }, offerMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, marginTop: 4 }, offerSalary: { color: Colors.green, fontSize: 18, fontWeight: '900' }, offerSalaryLabel: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8 }, offerObjective: { color: Colors.muted, fontSize: 9, lineHeight: 14, marginTop: 8 }, offerAction: { flexDirection: 'row', alignItems: 'center', gap: 18, marginTop: 14 }, offerActionTitle: { color: Colors.text, fontSize: 15, fontWeight: '900' }, offerActionCopy: { color: Colors.muted, fontSize: 10, lineHeight: 15, marginTop: 5, flex: 1 },
  contractTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', flexWrap: 'wrap', gap: 16 }, contractTitle: { color: Colors.text, fontSize: 25, fontWeight: '900', marginTop: 12 }, contractSubtitle: { color: Colors.muted, fontSize: 10, marginTop: 5 }, contractWorth: { color: Colors.orange, fontSize: 31, fontWeight: '900' }, contractWorthLabel: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8 }, metricGridInner: { flexDirection: 'row', flexWrap: 'wrap', gap: 17, marginTop: 25 }, negotiations: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginBottom: 20 }, negotiation: { minWidth: 230, flex: 1 }, negotiationTitle: { color: Colors.text, fontSize: 14, fontWeight: '900' }, negotiationCopy: { color: Colors.muted, fontSize: 9, marginVertical: 9 }, clauses: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  trainingSummary: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 }, trainingGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, trainingCard: { minWidth: 235, flexGrow: 1, flexBasis: 270 }, trainingTop: { flexDirection: 'row', justifyContent: 'space-between' }, trainingCost: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8 }, trainingName: { color: Colors.text, fontSize: 15, fontWeight: '900', marginTop: 13 }, trainingDescription: { color: Colors.muted, fontSize: 10, lineHeight: 15, marginTop: 5 }, trainingAttributes: { marginVertical: 12 }, trainingAttribute: { color: Colors.green, fontFamily: Fonts.mono, fontSize: 8, marginBottom: 4 },
  healthHero: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 18, marginBottom: 16 }, healthTitle: { color: Colors.text, fontSize: 21, fontWeight: '900', marginTop: 13 }, healthCopy: { color: Colors.muted, fontSize: 10, lineHeight: 16, marginTop: 6, maxWidth: 650 }, healthGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginBottom: 20 }, healthGauge: { minWidth: 190, flexGrow: 1, flexBasis: 220 }, healthGaugeTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 9 }, healthLabel: { color: Colors.text, fontSize: 11, fontWeight: '900' }, healthValue: { fontSize: 24, fontWeight: '900' }, healthStatus: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 7, marginTop: 7 },
  trophyHero: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 }, trophyGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, trophyCard: { minWidth: 230, flex: 1, alignItems: 'center', paddingVertical: 28 }, trophyIcon: { color: Colors.orange, fontSize: 42, marginBottom: 12 }, trophyName: { color: Colors.text, fontSize: 15, fontWeight: '900', textAlign: 'center', marginTop: 12 }, trophyMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, marginTop: 6 }, emptyPanel: { flex: 1 }, emptyTitle: { color: Colors.text, fontSize: 16, fontWeight: '900', marginBottom: 7 },
  rivalGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, rivalCard: { minWidth: 250, flexGrow: 1, flexBasis: 300 }, rivalTop: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 }, rivalCopy: { flex: 1, marginLeft: 11 }, rivalName: { color: Colors.text, fontSize: 13, fontWeight: '900' }, rivalMeta: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, marginTop: 4 }, rivalHeat: { color: Colors.red, fontSize: 23, fontWeight: '900' }, rivalStatus: { color: Colors.muted, fontFamily: Fonts.mono, fontSize: 8, marginTop: 8 },
});
